# -*- coding: utf-8 -*-
"""WSTRZYKIWANIE REGRESJI (testy mutacyjne) - czy walidator naprawde pilnuje napraw.

Kazda pozycja cofa JEDNA naprawe w kodzie (zamiana dokladnie jednego fragmentu), uruchamia walidator
i PRZYWRACA plik bajt w bajt (takze po bledzie). Wynik "WYKRYTE (n bledow)" znaczy, ze co najmniej
jedna asercja padla; "NIEWYKRYTE" znaczy, ze naprawy nie pilnuje zadna asercja - trzeba dopisac test.
"WZORZEC NIEAKTUALNY" znaczy, ze kod zmienil sie od czasu napisania mutacji - zaktualizowac albo
usunac pozycje.

Zasada projektu: po KAZDEJ zmianie zachowania dopisac mutacje cofajaca te zmiane i sprawdzic, ze
jest wykrywana. Zielony walidator bez tego niczego nie dowodzi (patrz Docs/DZIENNIK_ROZWOJU.md,
"asercja, ktora stala sie pusta przez wlasna naprawe").

UWAGA: w trakcie przebiegu NIE edytowac plikow Core/ ani walidatora - skrypt podmienia je na zywo.

Uzycie:
    python mutations.py                 # wszystkie (ok. 20 s na pozycje)
    python mutations.py M1 P3 C2        # wybrane, po pierwszym slowie nazwy
    python mutations.py --sprawdz       # tylko: czy wzorce nadal pasuja do kodu (bez uruchamiania)
"""
import io, re, subprocess, sys

SRC = 'D:/Games/RimWorld/Mods/ProceduralNarrator/Source/ProceduralNarrator/'
DEFS = 'D:/Games/RimWorld/Mods/ProceduralNarrator/Defs/'
WALIDATOR = 'D:/Games/RimWorld/Mods/ProceduralNarrator/Dev/Validator'

INJ = [
    # ---- polerowanie etapu 4 (2026-09-21), runda 1 ----
    ('I1 stara formula narracji (wspolny mnoznik z wieku najnowszego)', '{SRC}Core/Tension/TensionModel.cs',
     '            reading.Narrative = Curves.Clamp01(reading.NegativeLoad - reading.PositiveRelief);',
     '            reading.Narrative = Curves.Clamp01(-rhythmSource.ComputeRhythm(history).Charge)\n                * Curves.HalfLifeDecay(DaysSinceNewest(history, gameDay), parameters.halfLifeDays);'),
    ('I2 mianownik czlonu sytuacyjnego z ColonistCount', '{SRC}Core/Tension/TensionModel.cs',
     'par.downedFractionForMax * Math.Max(1, snapshot.ColonistsOnMap));',
     'par.downedFractionForMax * Math.Max(1, snapshot.ColonistCount));'),
    ('I3 straznik serii ignoruje kryzys', '{SRC}Core/Decision/SelectionPolicy.cs',
     '            return IsStreakAtLimit(context, passParams) && !context.ExtremeCrisis;',
     '            return IsStreakAtLimit(context, passParams);'),
    ('I4 cisza w kryzysie liczona jako swiadoma', '{SRC}Core/Decision/TurnRunner.cs',
     '                                       && !(context != null && context.ExtremeCrisis);',
     '                                       && true;'),
    ('I5 odkladanie rodzenstwa PO decyzji (stary licznik odlozonych)', '{SRC}Core/Decision/TurnRunner.cs',
     '                    potwierdzony = zwyciezca;\n                    potwierdzonyKlucz = Klucz(executionKey, zwyciezca);\n                    result.Accepted = true;\n                    break;',
     '                    potwierdzony = zwyciezca;\n                    potwierdzonyKlucz = Klucz(executionKey, zwyciezca);\n                    result.DeferredVariants += OdlozNiesprawdzalne(pool, zwyciezca, potwierdzonyKlucz,\n                                                                   executionKey, scopeKey);\n                    result.Accepted = true;\n                    break;'),
    ('I6 ApplyCrisis: moc nadpisana zerem zamiast min(x,0)', '{SRC}Core/Tension/IntentSelector.cs',
     '            decision.TargetIntensity = System.Math.Min(decision.TargetIntensity, 0f);',
     '            decision.TargetIntensity = 0f;'),
    ('I7 ApplyCrisis nie zmienia intencji', '{SRC}Core/Tension/IntentSelector.cs',
     '            decision.Intent = Intent.Breathe;\n            decision.TargetIntensity',
     '            decision.TargetIntensity'),
    ('I8 predykat kryzysu na porownaniu floatow', '{SRC}Core/Tension/CrisisDetector.cs',
     '            r.Extreme = p.enabled && r.Downed >= r.Threshold;',
     '            r.Extreme = p.enabled && r.Downed >= 1 && r.Downed >= p.downedFraction * r.Colonists;'),
    ('I9 kryzys wymaga zagrozenia (A3 zamiast A1)', '{SRC}Core/Tension/CrisisDetector.cs',
     '            r.Extreme = p.enabled && r.Downed >= r.Threshold;',
     '            r.Extreme = p.enabled && r.Downed >= r.Threshold && snapshot.Danger != DangerLevel.None;'),
    ('I10 zawieszenie straznika nie trafia do decyzji', '{SRC}Core/Decision/TurnRunner.cs',
     '            decyzja.StreakWaivedByCrisis = straznikZawieszony;',
     '            decyzja.StreakWaivedByCrisis = false;'),
    # ---- polerowanie etapu 4 (2026-09-21), runda 2 ----
    ('J16 cisza techniczna liczona jako swiadoma', '{SRC}Core/Decision/TurnRunner.cs',
     '            result.DeliberateSilence = decyzja.IsPass\n                                       && decyzja.PassReason == PassReason.Competitive\n                                       && !(context != null && context.ExtremeCrisis);',
     '            result.DeliberateSilence = decyzja.IsPass\n                                       && !(context != null && context.ExtremeCrisis);'),
    ('JM kryzys pomylony z zawieszeniem straznika', '{SRC}Core/Decision/TurnRunner.cs',
     '                                       && !(context != null && context.ExtremeCrisis);',
     '                                       && !straznikZawieszony;'),
    ('J8 kolumna straznikZawieszony stale true', '{SRC}Core/Decision/NarratorDecision.cs',
     '            Append(sb, "straznikZawieszony", StreakWaivedByCrisis ? "true" : "false");',
     '            Append(sb, "straznikZawieszony", "true");'),
    ('J15 slad zawieszenia zawsze', '{SRC}Core/Decision/TurnRunner.cs',
     '            if (straznikZawieszony)\n            {',
     '            if (true)\n            {'),
    ('J12 zawieszenie tylko przy ciszy', '{SRC}Core/Decision/TurnRunner.cs',
     '            decyzja.StreakWaivedByCrisis = straznikZawieszony;',
     '            decyzja.StreakWaivedByCrisis = straznikZawieszony && decyzja.IsPass;'),
    ('J2 minDowned ignorowany', '{SRC}Core/Tension/CrisisDetector.cs',
     '            r.Threshold = Math.Max(Math.Max(1, p.minDowned), progUlamkowy);',
     '            r.Threshold = Math.Max(1, progUlamkowy);'),
    ('J1 Sanitize kryzysu nic nie robi', '{SRC}Core/Tension/CrisisDetector.cs',
     '            var sb = new StringBuilder();\n            if (float.IsNaN(downedFraction) || float.IsInfinity(downedFraction))',
     '            var sb = new StringBuilder();\n            return sb.ToString();\n            if (float.IsNaN(downedFraction) || float.IsInfinity(downedFraction))'),
    ('J5 maxStreak=0 nie wylacza straznika', '{SRC}Core/Decision/SelectionPolicy.cs',
     '            if (passParams.maxStreak <= 0)\n            {\n                return false;\n            }\n            return context.History.DeliberateSilenceStreak >= passParams.maxStreak;',
     '            return context.History.DeliberateSilenceStreak >= passParams.maxStreak;'),
    ('J6 zawieszenie bez limitu serii', '{SRC}Core/Decision/SelectionPolicy.cs',
     '            return IsStreakAtLimit(context, passParams) && context.ExtremeCrisis;',
     '            return context != null && context.ExtremeCrisis;'),
    ('J17 lambda zastepcza 1.0 w ComputeAgedLoad', '{SRC}Core/Decision/Factors/Factor_DramaticContrast.cs',
     '            double sumNeg = 0.0;',
     '            if (double.IsNaN(tuning.lambda) || tuning.lambda < 0.0) lambda = 1.0;\n            double sumNeg = 0.0;'),
    ('J18 okno zastepcze 3 w ComputeAgedLoad', '{SRC}Core/Decision/Factors/Factor_DramaticContrast.cs',
     '            var load = new AgedLoad();\n            if (history == null || history.Count == 0)\n            {\n                return load;\n            }\n\n            int window = tuning.rhythmWindow > 0 ? tuning.rhythmWindow : 1;',
     '            var load = new AgedLoad();\n            if (history == null || history.Count == 0)\n            {\n                return load;\n            }\n\n            int window = tuning.rhythmWindow > 0 ? tuning.rhythmWindow : 3;'),
    ('J9 wpis z przyszlosci stygnie', '{SRC}Core/Decision/Factors/Factor_DramaticContrast.cs',
     '            double d = Curves.HalfLifeDecay(gameDay - e.GameDay, halfLifeDays);',
     '            double d = Curves.HalfLifeDecay(Math.Abs(gameDay - e.GameDay), halfLifeDays);'),
    ('J19 tenseAbove domyslne 0.48', '{SRC}Core/Tension/TensionParams.cs',
     '        public float tenseAbove = 0.60f;',
     '        public float tenseAbove = 0.48f;'),
    ('JP1 TurnPlanner gubi flage kryzysu', '{SRC}Core/Tension/TurnPlanner.cs',
     '                                                  plan.Tension.Tension, plan.Crisis.Extreme);',
     '                                                  plan.Tension.Tension, false);'),
    ('JP2 TurnPlanner pomija ApplyCrisis', '{SRC}Core/Tension/TurnPlanner.cs',
     '            plan.Intent = IntentSelector.ApplyCrisis(zamiar, plan.Crisis);',
     '            plan.Intent = zamiar;'),
    ('JK Kopia bez nowych pol', '{WALIDATOR}/Program.cs',
     '            AcuteDownedCount = s.AcuteDownedCount, ColonistsOnMap = s.ColonistsOnMap, Danger = s.Danger,',
     '            Danger = s.Danger,'),
    # ---- drugi przeglad etapu 4 (2026-09-22) ----
    ('M1 skladnik mocy stale 1', '{SRC}Core/Decision/Factors/Factor_IntentAlignment.cs',
     'float zgodnoscMocy = 1f - Math.Abs(mocKandydata - zadanaMoc) / IntensitySpan;',
     'float zgodnoscMocy = 1f;'),
    ('M2 odwrocony znak mocy', '{SRC}Core/Decision/Factors/Factor_IntentAlignment.cs',
     'float zgodnoscMocy = 1f - Math.Abs(mocKandydata - zadanaMoc) / IntensitySpan;',
     'float zgodnoscMocy = 1f - Math.Abs(mocKandydata + zadanaMoc) / IntensitySpan;'),
    ('M3 Hold celuje w +0.25', '{SRC}Core/Decision/Factors/Factor_IntentAlignment.cs',
     '                case Intent.Hold:\n                    return -0.30f;',
     '                case Intent.Hold:\n                    return 0.25f;'),
    ('M4 intensitySpan pominiety', '{SRC}Core/Tension/IntentSelector.cs',
     'decision.TargetIntensity = p.intensitySpan * (1f - 2f * Curves.Clamp01(tension));',
     'decision.TargetIntensity = 1.0f * (1f - 2f * Curves.Clamp01(tension));'),
    ('M5 Breathe celuje w 0.00', '{SRC}Core/Decision/Factors/Factor_IntentAlignment.cs',
     '                case Intent.Breathe:\n                    return 0.25f;',
     '                case Intent.Breathe:\n                    return 0.00f;'),
    ('P1 kryzys z parametrami null', '{SRC}Core/Tension/TurnPlanner.cs',
     'plan.Crisis = CrisisDetector.Evaluate(snapshot, crisisParams);',
     'plan.Crisis = CrisisDetector.Evaluate(snapshot, null);'),
    ('P6 kryzys z domyslnymi parametrami', '{SRC}Core/Tension/TurnPlanner.cs',
     'plan.Crisis = CrisisDetector.Evaluate(snapshot, crisisParams);',
     'plan.Crisis = CrisisDetector.Evaluate(snapshot, new CrisisParams());'),
    ('P2 Select na krzywej domyslnej', '{SRC}Core/Tension/TurnPlanner.cs',
     'IntentDecision zamiar = IntentSelector.Select(plan.Tension.Tension, tensionModel.Parameters);',
     'IntentDecision zamiar = IntentSelector.Select(plan.Tension.Tension, TensionParams.Default());'),
    ('P3 napiecie bez historii', '{SRC}Core/Tension/TurnPlanner.cs',
     'plan.Tension = tensionModel.Compute(history, snapshot, gameDay);',
     'plan.Tension = tensionModel.Compute(new EventHistory(), snapshot, gameDay);'),
    ('P8 napiecie bez dnia gry', '{SRC}Core/Tension/TurnPlanner.cs',
     'plan.Tension = tensionModel.Compute(history, snapshot, gameDay);',
     'plan.Tension = tensionModel.Compute(history, snapshot, 0f);'),
    ('P4 kontekst bez historii i dnia', '{SRC}Core/Tension/TurnPlanner.cs',
     'plan.Context = DecisionContext.Create(snapshot, history, gameDay,',
     'plan.Context = DecisionContext.Create(snapshot, new EventHistory(), 0f,'),
    ('C1 odczyt zeruje serie', '{SRC}Core/Model/EventHistory.cs',
     'this.deliberateSilenceStreak = deliberateSilenceStreak < 0 ? 0 : deliberateSilenceStreak;',
     'this.deliberateSilenceStreak = 0;'),
    ('C2 walencja zapisywana jako Neutral', '{SRC}Core/Model/EventHistoryEntry.cs',
     '                Valence.ToString(),',
     '                "Neutral",'),
    ('C3 licznik decyzji z zapisu ignorowany', '{SRC}Core/Model/EventHistory.cs',
     'this.decisionCount = decisionCount < 0 ? 0 : decisionCount;',
     'this.decisionCount = 0;'),
    ('C4 dzien gry formatem F0', '{SRC}Core/Model/EventHistoryEntry.cs',
     'GameDay.ToString("G9", CultureInfo.InvariantCulture),',
     'GameDay.ToString("F0", CultureInfo.InvariantCulture),'),
    ('C5 skala zapisywana jako Minor', '{SRC}Core/Model/EventHistoryEntry.cs',
     '                Scale.ToString()',
     '                "Minor"'),
    ('C6 payload gubiony przy odczycie', '{SRC}Core/Model/EventHistoryEntry.cs',
     '                ActionPayload = Unescape(parts[4]),',
     '                ActionPayload = null,'),
    ('C7 tick gubiony przy zapisie', '{SRC}Core/Model/EventHistoryEntry.cs',
     '                GameTick.ToString(CultureInfo.InvariantCulture),',
     '                "0",'),
    ('C8 numer enuma przepuszczany', '{SRC}Core/Model/EventHistoryEntry.cs',
     '            if (!Enum.IsDefined(typeof(T), parsed))\n            {\n                return false;\n            }',
     ''),
    ('R1 bez sortowania wpisow', '{SRC}Core/Model/EventHistory.cs',
     'while (j >= 0 && entries[j].DecisionIndex > biezacy.DecisionIndex)',
     'while (false)'),
    ('R2 bez przyciecia serii', '{SRC}Core/Model/EventHistory.cs',
     'if (this.deliberateSilenceStreak > decyzjiPoZdarzeniu)',
     'if (false)'),
    ('R3 bez przyciecia serii bez wpisow', '{SRC}Core/Model/EventHistory.cs',
     'else if (this.deliberateSilenceStreak > this.decisionCount)',
     'else if (false)'),
    ('K1 Clone gubi intensitySpan', '{SRC}Core/Tension/TensionParams.cs',
     '                tenseAbove = tenseAbove,\n                intensitySpan = intensitySpan',
     '                tenseAbove = tenseAbove'),
    ('K2 Clone wag gubi intentAlignment', '{SRC}Core/Decision/ScoringWeights.cs',
     '                dramaticContrast = dramaticContrast,\n                intentAlignment = intentAlignment\n            };',
     '                dramaticContrast = dramaticContrast\n            };'),
    ('K3 Sanitize tnie span do 1.0', '{SRC}Core/Tension/TensionParams.cs',
     'intensitySpan = Fix(intensitySpan, 0f, 2f, 1.0f, "intensitySpan", sb);',
     'intensitySpan = Fix(intensitySpan, 0f, 1f, 1.0f, "intensitySpan", sb);'),
    ('K4 profil awaryjny ignoruje wagi', '{SRC}Core/Tension/NarratorProfile.cs',
     'Weights = weights == null ? new ScoringWeights() : weights.Clone(),',
     'Weights = new ScoringWeights(),'),
    ('K5 profil awaryjny bez kopii', '{SRC}Core/Tension/NarratorProfile.cs',
     'Weights = weights == null ? new ScoringWeights() : weights.Clone(),',
     'Weights = weights == null ? new ScoringWeights() : weights,'),
    ('V1 stara etykieta RoundBudgetExhausted', '{SRC}Core/Decision/TurnRunner.cs',
     'else if (result.UnanswerableScopes > 0 && result.AcceptorCalls < maxRounds)',
     'else if (false)'),
    ('V2 VerdictUnavailable zawsze po petli', '{SRC}Core/Decision/TurnRunner.cs',
     'else if (result.UnanswerableScopes > 0 && result.AcceptorCalls < maxRounds)',
     'else if (true)'),

    # ---- krok 5, etap S1: katalog lukow, dopasowanie oczekiwanego typu, zgodnosc z intencja ----
    ('L8 faza negatywna steruje przy Breathe', '{SRC}Core/Arcs/ArcPhaseKind.cs',
     'return intent == Intent.Escalate || intent == Intent.Hold;',
     'return true;'),
    ('L9 faza pozytywna steruje przy Escalate', '{SRC}Core/Arcs/ArcPhaseKind.cs',
     'return intent == Intent.Hold || intent == Intent.Breathe || intent == Intent.Pass;',
     'return true;'),
    ('L10 faza neutralna czeka przy Breathe', '{SRC}Core/Arcs/ArcPhaseKind.cs',
     '                default:\n                    return true;',
     '                default:\n                    return intent != Intent.Breathe;'),
    ('L17 minimalna moc ignorowana', '{SRC}Core/Arcs/ArcExpectation.cs',
     'if ((int)e.Intensity < (int)minIntensity)',
     'if (false && (int)e.Intensity < (int)minIntensity)'),
    ('L18 wymagany tag ignorowany', '{SRC}Core/Arcs/ArcExpectation.cs',
     'if (!string.IsNullOrEmpty(requiredTag) && (e.Tags == null || !e.Tags.Contains(requiredTag)))',
     'if (false)'),
    ('L19 sameFaction ignorowane', '{SRC}Core/Arcs/ArcExpectation.cs',
     '            if (sameFaction)\n            {\n                if (!e.CarriesFaction)',
     '            if (false)\n            {\n                if (!e.CarriesFaction)'),
    ('L36 tagi z pierwszego klocka zamiast z akcji', '{SRC}Core/Arcs/ArcExpectation.cs',
     'if (b != null && b.Type == BlockType.Action)',
     'if (b != null)'),
    ('L31 oczekiwanie bez walencji przepuszczone', '{SRC}Core/Arcs/ArcCatalog.cs',
     'if (e.valences == null || e.valences.Count == 0)',
     'if (false)'),
    ('L32 przejscie w miejscu przepuszczone', '{SRC}Core/Arcs/ArcCatalog.cs',
     'else if (j <= phaseIndex)',
     'else if (j < phaseIndex)'),
    ('L33 luki wiazace frakcje w roznych grupach', '{SRC}Core/Arcs/ArcCatalog.cs',
     'if (wiazace.Count > 0 && (grupy.Count > 1 || string.IsNullOrEmpty(grupy[0])))',
     'if (false)'),
    ('L34 nieistniejacy nastepnik przepuszczony', '{SRC}Core/Arcs/ArcCatalog.cs',
     'if (!ids.Contains(a.successor) || string.Equals(a.successor, a.defName, StringComparison.Ordinal))',
     'if (string.Equals(a.successor, a.defName, StringComparison.Ordinal))'),
    ('L35 {FRAKCJA} przed zwiazaniem przepuszczone', '{SRC}Core/Arcs/ArcCatalog.cs',
     'if (Mentions(f.message) && (pierwszaWiazaca < 0 || pierwszaWiazaca > i))',
     'if (false)'),
    ('L37 sameFaction bez wiazania przepuszczone', '{SRC}Core/Arcs/ArcCatalog.cs',
     'if (e.sameFaction && (i == 0 || pierwszaWiazaca < 0 || pierwszaWiazaca >= i))',
     'if (false)'),
    ('L38 kolejnosc katalogu rosnaco po priorytecie', '{SRC}Core/Arcs/ArcCatalog.cs',
     'arcs = valid.OrderByDescending(a => a.priority)',
     'arcs = valid.OrderBy(a => a.priority)'),
    ('L39 bledne luki zostaja w katalogu', '{SRC}Core/Arcs/ArcCatalog.cs',
     'var valid = all.Where(a => !bad.Contains(a)).ToList();',
     'var valid = all.ToList();'),

    # ---- krok 5, etap S2: automat lukow, kodek, potwierdzanie wykonania ----
    ('L12 niewykonane zdarzenie przesuwa luk', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     'return s == ExecStatus.Executed || s == ExecStatus.Simulated || s == ExecStatus.LateExecuted;',
     'return s != ExecStatus.Ambiguous;'),
    ('L13 niejednoznaczne liczone jako wykonane', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     'return s == ExecStatus.Executed || s == ExecStatus.Simulated || s == ExecStatus.LateExecuted;',
     'return s != ExecStatus.NotExecuted && s != ExecStatus.LateNotExecuted;'),
    ('L40 odpalenie w tym samym ticku przez innego nie jest niejednoznaczne', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     '            if (lastFireBefore == tick)\n            {\n                return ExecStatus.Ambiguous;\n            }\n',
     ''),
    # Krok 6: klasyfikacja spozniona przeniesiona do wspolnej implementacji (luki i fakty) -
    # ta sama mutacja, nowy wzorzec.
    ('L41 pozne nadpisane odpalenie = niewykonane', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     'return lastFireNow > decisionTick ? ExecStatus.Ambiguous : ExecStatus.LateNotExecuted;',
     'return ExecStatus.LateNotExecuted;'),
    ('L14 limit lukow o jeden za duzy', '{SRC}Core/Arcs/ArcDirector.cs',
     'if (ledger.Active.Count >= prms.maxConcurrent)',
     'if (ledger.Active.Count > prms.maxConcurrent)'),
    ('L15 grupa wykluczajaca ignorowana', '{SRC}Core/Arcs/ArcDirector.cs',
     'if (!string.IsNullOrEmpty(def.exclusionGroup) && ledger.Active.Any(a =>',
     'if (false && ledger.Active.Any(a =>'),
    ('L16 odstep po zamknieciu ignorowany', '{SRC}Core/Arcs/ArcDirector.cs',
     'now.GameDay - zamkniety < def.cooldownDays)',
     'now.GameDay - zamkniety < 0f)'),
    ('L21 dojrzalosc fazy ignorowana', '{SRC}Core/Arcs/ArcDirector.cs',
     'return gameDay - inst.PhaseEnteredDay >= phase.minDaysAfterPrevious;',
     'return true;'),
    ('L22 limit Rozwiazania nie zamyka luku', '{SRC}Core/Arcs/ArcDirector.cs',
     'if (faza.kind == ArcPhaseKind.Resolution)',
     'if (false)'),
    ('L24 baza strat nie resetowana przy wejsciu w faze', '{SRC}Core/Arcs/ArcDirector.cs',
     'inst.BaseColonistLosses = now.ColonistLosses;',
     'inst.BaseColonistLosses = 0;'),
    ('L25 warunki startu ignorowane', '{SRC}Core/Arcs/ArcDirector.cs',
     'if (snapshot == null || !def.StartConditionsMet(snapshot, out niespelniony))',
     'if (snapshot == null)'),
    ('L42 straznicy fazy ignorowani', '{SRC}Core/Arcs/ArcDirector.cs',
     't = FirstHolding(faza.transitions, now, inst);',
     't = null;'),
    ('L43 przejscia calego luku ignorowane', '{SRC}Core/Arcs/ArcDirector.cs',
     'ArcTransition t = FirstHolding(def.transitions, now, inst);',
     'ArcTransition t = null;'),
    ('L45 nastepnik nie otwierany', '{SRC}Core/Arcs/ArcDirector.cs',
     'TryOpen(ledger, nastepca, null, snapshot, now, ReasonSuccessor, wynik);',
     'nastepca = null;'),
    ('L46 luk wiazacy frakcje otwiera sie bez frakcji', '{SRC}Core/Arcs/ArcDirector.cs',
     '                    if (string.IsNullOrEmpty(executed.FactionId))\n                    {\n                        return false;\n                    }\n                    frakcja = executed.FactionId;',
     '                    frakcja = executed.FactionId;'),
    ('L47 wejscie w faze nie przestawia zegara fazy', '{SRC}Core/Arcs/ArcDirector.cs',
     'inst.PhaseEnteredDay = now.GameDay;',
     'inst.PhaseEnteredDay = inst.OpenedDay;'),
    ('L48 Reconcile zostawia nieznane instancje', '{SRC}Core/Arcs/ArcDirector.cs',
     '                if (idx <= 0)\n                {\n                    ledger.Active.Remove(inst);',
     '                if (false)\n                {\n                    ledger.Active.Remove(inst);'),
    ('L49 szczyt zagrozenia nie sledzony', '{SRC}Core/Arcs/ArcDirector.cs',
     'if ((int)now.Danger > (int)inst.PeakDanger)',
     'if (false)'),
    ('L26 kodek gubi zwiazana frakcje', '{SRC}Core/Arcs/ArcInstance.cs',
     '                Escape(BoundFactionId),',
     '                Escape(null),'),
    ('L27 kodek przestawia faze na zasiew', '{SRC}Core/Arcs/ArcInstance.cs',
     '                PhaseId = phaseId,',
     '                PhaseId = "Zasiew",'),
    ('L50 numer instancji nie podnoszony nad otwarte', '{SRC}Core/Arcs/ArcLedger.cs',
     'if (a.Number >= NextNumber)',
     'if (false)'),

    # ---- krok 5, etap S3: luk w warstwie decyzyjnej (premia tylko w koncowym wyborze) ----
    ('L1 ocena akcji z Utility zamiast SelectionScore', '{SRC}Core/Decision/ActionWeighting.cs',
     'g = new ActionGroup { ActionId = klucz, Score = k.SelectionScore };',
     'g = new ActionGroup { ActionId = klucz, Score = k.Utility };'),
    ('L60 maksimum grupy tylko z pierwszego wariantu', '{SRC}Core/Decision/ActionWeighting.cs',
     'else if (k.SelectionScore > g.Score)',
     'else if (false)'),
    ('L2 losowanie wariantu z Utility', '{SRC}Core/Decision/SelectionPolicy.cs',
     'uWariantow[v] = warianty[v].SelectionScore;',
     'uWariantow[v] = warianty[v].Utility;'),
    ('L3 p laczne z Utility', '{SRC}Core/Decision/SelectionPolicy.cs',
     'u[v] = grupa.Variants[v].SelectionScore;',
     'u[v] = grupa.Variants[v].Utility;'),
    ('L6 premia stala zamiast szerokosci pasma', '{SRC}Core/Decision/SelectionPolicy.cs',
     'float premiaLuku = best - progPasma;',
     'float premiaLuku = 0.1f;'),
    ('L56 lukWPasmie nieustawiane', '{SRC}Core/Decision/SelectionPolicy.cs',
     'ArcMatchedInBand = lukStosowany ? lukowychWPasmie : -1,',
     'ArcMatchedInBand = -1,'),
    ('L57 kolumna premiaLuku zerowa', '{SRC}Core/Decision/NarratorDecision.cs',
     'Append(sb, "premiaLuku", lukowy ? Fmt(w.ArcBonus) : string.Empty);',
     'Append(sb, "premiaLuku", lukowy ? Fmt(0f) : string.Empty);'),
    ('L55 ScoreAll nie nadaje wartosci lukowych', '{SRC}Core/Decision/UtilityScorer.cs',
     'context.ArcFocus.Apply(wynik);',
     'wynik.TrimExcess();'),
    ('L7 zawetowani dostaja wartosc lukowa', '{SRC}Core/Arcs/ArcFocus.cs',
     'if (k == null || k.IsPass || k.Vetoed || k.Event == null)',
     'if (k == null || k.IsPass || k.Event == null)'),
    ('L20 suma po lukach zamiast maksimum', '{SRC}Core/Arcs/ArcFocus.cs',
     '                        wartosc = 1f;',
     '                        wartosc += 1f;'),
    ('L30 brak wstrzymania, gdy nic nie pasuje', '{SRC}Core/Arcs/ArcFocus.cs',
     'if (Matched == 0)',
     'if (false)'),
    ('L51 walencja kandydata nie sprawdzana', '{SRC}Core/Arcs/ArcFocus.cs',
     'if (!ArcIntentRules.Compatible(e.Valence, Intent))',
     'if (false)'),
    ('L53 wiazanie frakcji mimo nieuzytecznosci', '{SRC}Core/Arcs/ArcFocus.cs',
     '                                && (usability == null || usability.UsableAt(zwiazana, e.Intensity));',
     '                                ;'),
    ('L52 faza niedojrzala steruje', '{SRC}Core/Arcs/ArcDirector.cs',
     'Active = dojrzala && zgodna,',
     'Active = zgodna,'),
    ('L58 status fazy bez intencji', '{SRC}Core/Arcs/ArcDirector.cs',
     '&& e.valences.Any(v => ArcIntentRules.Compatible(v, intent)));',
     '&& e.valences.Count > 0);'),
    ('L29 planner ignoruje luki', '{SRC}Core/Tension/TurnPlanner.cs',
     ': arcs.BuildFocus(ledger, plan.Intent.Intent, gameDay, usability);',
     ': null;'),

    # ---- krok 6, etap S1: blackboard (fakty, slad po zamknietym watku, fasada) ----
    ('B1 fakty bez sortowania ordynalnego (kolejnosc slownika)', '{SRC}Core/Blackboard/FactLedger.cs',
     '            return facts.Values\n                        .Where(f => f.IsActive(nowDay))\n                        .OrderBy(f => f.Key, StringComparer.Ordinal)\n                        .ToList();',
     '            return facts.Values.Where(f => f.IsActive(nowDay)).ToList();'),
    ('B2 linie zapisu faktow bez sortowania', '{SRC}Core/Blackboard/FactLedger.cs',
     '            return facts.Values\n                        .OrderBy(f => f.Key, StringComparer.Ordinal)\n                        .Select(f => f.Encode())\n                        .ToList();',
     '            return facts.Values.Select(f => f.Encode()).ToList();'),
    ('B3 wygasanie czyszczace zamiast leniwego', '{SRC}Core/Blackboard/FactLedger.cs',
     '        public List<Fact> Active(float nowDay)\n        {\n            return facts.Values',
     '        public List<Fact> Active(float nowDay)\n        {\n            foreach (string k in facts.Where(p => !p.Value.IsActive(nowDay)).Select(p => p.Key).ToList())\n            {\n                facts.Remove(k);\n            }\n            return facts.Values'),
    ('B4 granica czasu zycia bez tolerancji (szum float32)', '{SRC}Core/Blackboard/FactLedger.cs',
     '            return nowDay - SetDay < LifespanDays - FactLedger.BoundaryToleranceDays;',
     '            return nowDay - SetDay < LifespanDays;'),
    ('B5 brak faktu daje wiek zamiast -1', '{SRC}Core/Blackboard/FactLedger.cs',
     '            if (!facts.TryGetValue(key, out f) || !f.IsActive(nowDay))\n            {\n                return -1f;\n            }',
     '            if (!facts.TryGetValue(key, out f) || !f.IsActive(nowDay))\n            {\n                return nowDay;\n            }'),
    ('B6 licznik sumuje sie z okresem, ktory wygasl', '{SRC}Core/Blackboard/FactLedger.cs',
     '                if (facts.TryGetValue(key, out stary) && stary.IsActive(nowDay))',
     '                if (facts.TryGetValue(key, out stary))'),
    ('B7 klucz faktu bez alfabetu (literowka przechodzi)', '{SRC}Core/Blackboard/FactLedger.cs',
     '            if (string.IsNullOrEmpty(key) || key.Length > 64)\n            {\n                return false;\n            }',
     '            if (string.IsNullOrEmpty(key))\n            {\n                return false;\n            }\n            return true;'),
    ('B8 postac kanoniczna faktow bez separatora wiodacego', '{SRC}Core/Blackboard/FactLedger.cs',
     '            var sb = new System.Text.StringBuilder();\n            sb.Append(PairSeparator);',
     '            var sb = new System.Text.StringBuilder();'),
    ('B9 zamkniecie watku nie zapisywane do ksiegi', '{SRC}Core/Arcs/ArcDirector.cs',
     '            ledger.RecordClosure(inst, outcome, now.GameDay);',
     '            if (inst == null) { ledger.RecordClosure(inst, outcome, now.GameDay); }'),
    ('B10 ewikcja zamkniec od najnowszego', '{SRC}Core/Arcs/ArcLedger.cs',
     '                Closed.RemoveAt(ofiara);',
     '                Closed.RemoveAt(Closed.Count - 1);'),
    ('B11 postac kanoniczna watkow ze statusem na koncu', '{SRC}Core/Blackboard/NarratorBlackboard.cs',
     '            sb.Append(EntrySeparator).Append(status).Append(PartSeparator)\n              .Append(id).Append(PartSeparator).Append(ogon ?? string.Empty);',
     '            sb.Append(EntrySeparator).Append(id).Append(PartSeparator)\n              .Append(ogon ?? string.Empty).Append(PartSeparator).Append(status);'),
    ('B12 tury bez tematu: brak w buforze jak "bardzo dawno"', '{SRC}Core/Blackboard/NarratorBlackboard.cs',
     '            return BeyondHorizon;\n        }\n\n        // --- POSTACIE KANONICZNE',
     '            return int.MaxValue;\n        }\n\n        // --- POSTACIE KANONICZNE'),
    ('B13 postac kanoniczna watkow pokazuje wszystkie zamkniecia, nie ostatnie', '{SRC}Core/Blackboard/NarratorBlackboard.cs',
     '                    ostatnie[z.ArcId] = z;',
     '                    if (!ostatnie.ContainsKey(z.ArcId)) { ostatnie[z.ArcId] = z; }'),

    # ---- krok 6, etap S2: warunki czytajace pamiec przez snapshot ----
    ('B14 Cond_Fakt sprawdza obecnosc przez wartosc (fakt o wartosci 0 znika)', '{SRC}Core/Conditions/HardConditions.cs',
     '            return NarratorBlackboard.FactPresentIn(s.Facts, key) == required;',
     '            float v = NarratorBlackboard.FactValueFrom(s.Facts, key);\n            return (!float.IsNaN(v) && v != 0f) == required;'),
    ('B15 Cond_FaktOd: brak faktu traktowany jak bardzo stary', '{SRC}Core/Conditions/HardConditions.cs',
     '            return !float.IsNaN(wiek) && wiek >= minDays - FactLedger.BoundaryToleranceDays;',
     '            return float.IsNaN(wiek) || wiek >= minDays - FactLedger.BoundaryToleranceDays;'),
    ('B16 Cond_TurBezTematu ignoruje deklaracje o horyzoncie', '{SRC}Core/Conditions/HardConditions.cs',
     '            if (tur == NarratorBlackboard.BeyondHorizon)\n            {\n                return beyondHorizonCounts;\n            }',
     '            if (tur == NarratorBlackboard.BeyondHorizon)\n            {\n                return true;\n            }'),
    ('B17 Cond_WatekZamkniety ignoruje zadany wynik', '{SRC}Core/Conditions/HardConditions.cs',
     '            return string.IsNullOrEmpty(outcome) || string.Equals(wynik, outcome, StringComparison.Ordinal);',
     '            return true;'),
    ('B18 postac kanoniczna faktow niesie dzien ustawienia zamiast wieku', '{SRC}Core/Blackboard/FactLedger.cs',
     '                float wiek = nowDay - f.SetDay;',
     '                float wiek = f.SetDay;'),
    ('B19 Cond_FaktLiczba przepuszcza brak faktu', '{SRC}Core/Conditions/HardConditions.cs',
     '            float v = NarratorBlackboard.FactValueFrom(s.Facts, key);\n            return !float.IsNaN(v) && v >= min && v <= max;',
     '            float v = NarratorBlackboard.FactValueFrom(s.Facts, key);\n            return float.IsNaN(v) || (v >= min && v <= max);'),

    # ---- krok 6, etap S3: slot konsekwencji ----
    ('B20 slot konsekwencji poza sygnatura', '{SRC}Core/Composition/EventComposer.cs',
     '            BlockType.Trigger, BlockType.Actor, BlockType.Action, BlockType.Target, BlockType.Modifier,\n            BlockType.Consequence',
     '            BlockType.Trigger, BlockType.Actor, BlockType.Action, BlockType.Target, BlockType.Modifier'),
    ('B21 slot konsekwencji wymagany zamiast opcjonalnego', '{SRC}Core/Composition/EventComposer.cs',
     'return type == BlockType.Trigger || type == BlockType.Modifier || type == BlockType.Consequence;',
     'return type == BlockType.Trigger || type == BlockType.Modifier;'),
    ('B22 slot konsekwencji poza enumeracja', '{SRC}Core/Composition/EventComposer.cs',
     '            BlockType.Actor, BlockType.Target, BlockType.Trigger, BlockType.Modifier, BlockType.Consequence',
     '            BlockType.Actor, BlockType.Target, BlockType.Trigger, BlockType.Modifier'),
    ('B23 slot konsekwencji poza TryCompose (druga sciezka kompozycji)', '{SRC}Core/Composition/EventComposer.cs',
     'private static readonly BlockType[] OptionalSlots = { BlockType.Trigger, BlockType.Modifier, BlockType.Consequence };',
     'private static readonly BlockType[] OptionalSlots = { BlockType.Trigger, BlockType.Modifier };'),

    # ---- krok 6, etap S4: katalog konsekwencji i fakty w warunkach startu lukow ----
    ('B24 klocek nie niesie deklaracji faktow do kandydata', '{SRC}Core/Model/Block.cs',
     '        public List<FactWrite> FactsOnExecute = new List<FactWrite>();',
     '        public List<FactWrite> FactsOnExecute { get { return new List<FactWrite>(); } }'),

    # ---- krok 6, etap S5: kolejka faktow (zapis po potwierdzonym wykonaniu, w nastepnym wywolaniu) ----
    ('B25 kolejka faktow stosowana w tym samym ticku co decyzja', '{SRC}Core/Blackboard/FactLedger.cs',
     '            if (p == null || p.Tick >= nowTick)\n            {\n                return wynik;\n            }',
     '            if (p == null)\n            {\n                return wynik;\n            }'),
    ('B26 fakt ostemplowany dniem zastosowania zamiast dnia decyzji', '{SRC}Core/Blackboard/FactLedger.cs',
     '                bool ok = w.ApplyTo(this, p.Day);',
     '                bool ok = w.ApplyTo(this, nowTick / 60000f);'),
    ('B27 potwierdzenie cudzej decyzji oznacza kolejke', '{SRC}Core/Blackboard/FactLedger.cs',
     '            if (p == null || p.DecisionIndex != decisionIndex || p.Tick != tick)\n            {\n                return null;\n            }',
     '            if (p == null)\n            {\n                return null;\n            }'),
    ('B28 spoznione: brak sladu odpalenia traktowany jak wykonanie', '{SRC}Core/Blackboard/FactLedger.cs',
     '                if (!ExecutionConfirmation.CountsAsExecuted(st))\n                {\n                    Pending = null;',
     '                if (false)\n                {\n                    Pending = null;'),
    ('B29 kolejka przyjmuje deklaracje o zlym kluczu', '{SRC}Core/Blackboard/FactLedger.cs',
     '                if (w != null && IsValidKey(w.key) && !float.IsNaN(w.value) && !float.IsInfinity(w.value)',
     '                if (w != null && !float.IsNaN(w.value) && !float.IsInfinity(w.value)'),
    ('B30 kodek kolejki gubi potwierdzenie', '{SRC}Core/Blackboard/PendingFacts.cs',
     '                Confirmed = f[6] == "1",',
     '                Confirmed = false,'),
    ('B31 zapis przyjmuje druga kolejke', '{SRC}Core/Blackboard/FactLedger.cs',
     '                    if (Pending == null && PendingFacts.TryDecode(line, out p))',
     '                    if (PendingFacts.TryDecode(line, out p))'),
    ('B32 zapis gry gubi kolejke faktow', '{SRC}Core/Blackboard/FactLedger.cs',
     '            if (Pending != null)\n            {\n                linie.Add(Pending.Encode());\n            }',
     '            if (Pending == null)\n            {\n                linie.Add(string.Empty);\n            }'),
    ('B33 niewykonane na sciezce normalnej zostawia kolejke', '{SRC}Core/Blackboard/FactLedger.cs',
     '            Pending = null;\n            return new FactEvent\n            {\n                Kind = FactEventKind.Dropped, Day = p.Day, SourceTick = p.Tick, SourceDecision = p.DecisionIndex,',
     '            return new FactEvent\n            {\n                Kind = FactEventKind.Dropped, Day = p.Day, SourceTick = p.Tick, SourceDecision = p.DecisionIndex,'),
    ('B34 kolumna konsekwencji bez rozroznienia pustego slotu', '{SRC}Core/Decision/NarratorDecision.cs',
     '            return "-";\n        }\n\n        private static string Fmt(float v)',
     '            return string.Empty;\n        }\n\n        private static string Fmt(float v)'),
    # ---- S6 kroku 6 (2026-09-23): przeglad adwersarialny - luki w testach i poprawki rdzenia ----
    ('B35 granica wlaczajaca, bez tolerancji', '{SRC}Core/Blackboard/FactLedger.cs',
     '            return nowDay - SetDay < LifespanDays - FactLedger.BoundaryToleranceDays;',
     '            return nowDay - SetDay <= LifespanDays;'),
    ('B36 Cond_FaktOd bez tolerancji granicy', '{SRC}Core/Conditions/HardConditions.cs',
     '            return !float.IsNaN(wiek) && wiek >= minDays - FactLedger.BoundaryToleranceDays;',
     '            return !float.IsNaN(wiek) && wiek >= minDays;'),
    ('B37 kolejka potwierdzana tylko werdyktem Executed (symulator traci fakty)', '{SRC}Core/Blackboard/FactLedger.cs',
     '            if (ExecutionConfirmation.CountsAsExecuted(status))\n            {\n                p.Confirmed = true;',
     '            if (status == ExecStatus.Executed)\n            {\n                p.Confirmed = true;'),
    ('B38 spoznione niejednoznaczne stosuje fakty', '{SRC}Core/Blackboard/FactLedger.cs',
     '                if (!ExecutionConfirmation.CountsAsExecuted(st))',
     '                if (st == ExecStatus.LateNotExecuted)'),
    ('B39 FactEvent.Value = przyrost zamiast stanu', '{SRC}Core/Blackboard/FactLedger.cs',
     '                    Value = ok ? ValueOf(w.key, p.Day, float.NaN) : float.NaN,',
     '                    Value = ok ? w.value : float.NaN,'),
    ('B40 dekoder kolejki gubi wartosc deklaracji', '{SRC}Core/Blackboard/PendingFacts.cs',
     'zapisy.Add(new FactWrite { key = p[0], value = wartosc, accumulate = p[2] == "1", lifespanDays = zycie });',
     'zapisy.Add(new FactWrite { key = p[0], value = 1f, accumulate = p[2] == "1", lifespanDays = zycie });'),
    ('B41 dekoder kolejki: tryb zawsze licznik', '{SRC}Core/Blackboard/PendingFacts.cs',
     'zapisy.Add(new FactWrite { key = p[0], value = wartosc, accumulate = p[2] == "1", lifespanDays = zycie });',
     'zapisy.Add(new FactWrite { key = p[0], value = wartosc, accumulate = true, lifespanDays = zycie });'),
    ('B42 dekoder kolejki gubi czas zycia', '{SRC}Core/Blackboard/PendingFacts.cs',
     'zapisy.Add(new FactWrite { key = p[0], value = wartosc, accumulate = p[2] == "1", lifespanDays = zycie });',
     'zapisy.Add(new FactWrite { key = p[0], value = wartosc, accumulate = p[2] == "1", lifespanDays = 20f });'),
    ('B43 stratny zapis dnia faktu (0.#)', '{SRC}Core/Blackboard/FactLedger.cs',
     'SetDay.ToString("G9", CultureInfo.InvariantCulture)',
     'SetDay.ToString("0.#", CultureInfo.InvariantCulture)'),
    ('B44 stratny zapis dnia kolejki (0.#)', '{SRC}Core/Blackboard/PendingFacts.cs',
     '+ ArcInstance.FieldSeparator + Day.ToString("G9", CultureInfo.InvariantCulture)',
     '+ ArcInstance.FieldSeparator + Day.ToString("0.#", CultureInfo.InvariantCulture)'),
    ('B45 FactCountIn liczy o jeden za duzo', '{SRC}Core/Blackboard/NarratorBlackboard.cs',
     '            return n;',
     '            return n + 1;'),
    ('B46 spoznione: lastFireOf bez nazwy incydentu', '{SRC}Core/Blackboard/FactLedger.cs',
     'int teraz = lastFireOf == null ? -1 : lastFireOf(p.IncidentDefName);',
     'int teraz = lastFireOf == null ? -1 : lastFireOf(null);'),
    ('B47 klucz bez reguly pierwszego znaku', '{SRC}Core/Blackboard/FactLedger.cs',
     "            if (!((c0 >= 'a' && c0 <= 'z') || (c0 >= 'A' && c0 <= 'Z') || (c0 >= '0' && c0 <= '9')))",
     '            if (false)'),
    ('B48 przycinanie zamkniec bez oszczedzania rzadkich lukow', '{SRC}Core/Arcs/ArcLedger.cs',
     '                    if (MaNowszyWpis(i))',
     '                    if (false)'),
    ('B49 wczytanie zamkniec zostawia najstarsze', '{SRC}Core/Arcs/ArcLedger.cs',
     '                    if (ArcClosure.TryDecode(line, out z))\n                    {',
     '                    if (ArcClosure.TryDecode(line, out z) && Closed.Count < MaxClosed)\n                    {'),
    ('B50 nakladka nie przywraca wieku tematow', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     '            spozniony.TurnsSinceThemes = DecisionTurnsSinceThemes ?? string.Empty;',
     '            // (mutacja: wiek tematow nie nalozony)'),
    ('B51 kodek P gubi pamiec decyzji', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     '                pamiec = true;',
     '                pamiec = false;'),
    ('B52 kodek P odrzuca stara linie 15 pol', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     '            if ((f.Length != FieldCount && f.Length != S6FieldCount && f.Length != LegacyFieldCount) || f[0] != LineTag)',
     '            if ((f.Length != FieldCount && f.Length != S6FieldCount) || f[0] != LineTag)'),
    ('B53 katalog przepuszcza nastepnika pytajacego o poprzednika', '{SRC}Core/Arcs/ArcCatalog.cs',
     '                    if (WatkiWarunkow(nast).Any(w => string.Equals(w, poprzednik.defName, StringComparison.Ordinal)))',
     '                    if (false)'),
    ('B54 katalog przepuszcza warunek watku z nieznanym lukiem', '{SRC}Core/Arcs/ArcCatalog.cs',
     '                    string brak = WatkiWarunkow(a).FirstOrDefault(w => !validIds.Contains(w));',
     '                    string brak = null;'),
    ('B55 katalog przepuszcza zly wynik zamkniecia', '{SRC}Core/Arcs/ArcCatalog.cs',
     '                    string zlyWynik = ZlyWynikZamkniecia(a, all);',
     '                    string zlyWynik = null;'),
    ('B56 katalog sprawdza klucz faktu tylko na pustosc', '{SRC}Core/Arcs/ArcCatalog.cs',
     '&& !FactLedger.IsValidKey(klucz))',
     '&& string.IsNullOrEmpty(klucz))'),
    ('B57 czas zycia ponizej dnia uznany za uzyteczny', '{SRC}Core/Blackboard/FactLedger.cs',
     '(lifespanDays <= 0f || lifespanDays >= 1f)',
     '(lifespanDays <= 0f || lifespanDays > 0f)'),
    ('B58 Cond_TurBezTematu: poza horyzontem domyslnie nie liczy sie', '{SRC}Core/Conditions/HardConditions.cs',
     '        public bool beyondHorizonCounts = true;',
     '        public bool beyondHorizonCounts = false;'),
    # ---- S6 kroku 6: mutacje TRESCI (Defs) i listy plikow walidatora ----
    ('X1 Trofea przestaja pisac walka.byla', '{DEFS}Blocks/Blocks_Consequences.xml',
     '<key>lupy.zebrane</key>\n        <value>1</value>\n        <accumulate>true</accumulate>\n        <lifespanDays>20</lifespanDays>\n      </li>\n      <li>\n        <key>walka.byla</key>',
     '<key>lupy.zebrane</key>\n        <value>1</value>\n        <accumulate>true</accumulate>\n        <lifespanDays>20</lifespanDays>\n      </li>\n      <li>\n        <key>walka.bylo</key>'),
    ('X2 ZnakNaNiebie pisze inny klucz', '{DEFS}Blocks/Blocks_Consequences.xml',
     '        <key>niebo.znak</key>',
     '        <key>niebo.znaki</key>'),
    ('X3 Znaki z nieba bez warunku faktowego', '{DEFS}Arcs/Arcs_Core.xml',
     '      <li Class="ProceduralNarrator.Core.Conditions.Cond_Fakt">\n        <key>niebo.znak</key>\n      </li>',
     ''),
    ('X4 usuniety zakaz Wrak x Uchodzcy', '{DEFS}Blocks/Blocks_Consequences.xml',
     'kapsula znika bez wraku, wiec "zostaje to, co spadlo" i fakt wrak.lezy bylyby falszem. -->\n      <li>PN_Akcja_Uchodzcy</li>',
     'kapsula znika bez wraku, wiec "zostaje to, co spadlo" i fakt wrak.lezy bylyby falszem. -->'),
    ('X5 konsekwencja z intensywnoscia High', '{DEFS}Blocks/Blocks_Consequences.xml',
     '    <defName>PN_Kons_Plotki</defName>\n    <blockType>Consequence</blockType>',
     '    <defName>PN_Kons_Plotki</defName>\n    <blockType>Consequence</blockType>\n    <intensity>High</intensity>'),
    ('X6 pisarze walka.byla niezgodni co do czasu zycia', '{DEFS}Blocks/Blocks_Consequences.xml',
     '      <li>\n        <key>walka.byla</key>\n        <value>1</value>\n        <accumulate>true</accumulate>\n        <lifespanDays>20</lifespanDays>\n      </li>\n    </factsOnExecute>\n    <incompatibleWith>\n      <li>PN_Akcja_Wedrowiec</li>\n      <li>PN_Akcja_Zrzut</li>\n      <li>PN_Akcja_Okup</li>\n      <li>PN_Akcja_Uchodzcy</li>\n      <li>PN_Akcja_Dzikus</li>\n      <li>PN_Akcja_Ambrozja</li>\n      <li>PN_Akcja_Meteoryt</li>\n      <li>PN_Akcja_Burza</li>\n      <li>PN_Akcja_Emanator</li>\n    </incompatibleWith>\n  </ProceduralNarrator.Integration.Defs.NarrativeBlockDef>\n\n  <!-- ============================ PO PRZYBYSZU',
     '      <li>\n        <key>walka.byla</key>\n        <value>1</value>\n        <accumulate>true</accumulate>\n        <lifespanDays>25</lifespanDays>\n      </li>\n    </factsOnExecute>\n    <incompatibleWith>\n      <li>PN_Akcja_Wedrowiec</li>\n      <li>PN_Akcja_Zrzut</li>\n      <li>PN_Akcja_Okup</li>\n      <li>PN_Akcja_Uchodzcy</li>\n      <li>PN_Akcja_Dzikus</li>\n      <li>PN_Akcja_Ambrozja</li>\n      <li>PN_Akcja_Meteoryt</li>\n      <li>PN_Akcja_Burza</li>\n      <li>PN_Akcja_Emanator</li>\n    </incompatibleWith>\n  </ProceduralNarrator.Integration.Defs.NarrativeBlockDef>\n\n  <!-- ============================ PO PRZYBYSZU'),
    ('X7 czas zycia faktu ponizej dnia', '{DEFS}Blocks/Blocks_Consequences.xml',
     '        <lifespanDays>15</lifespanDays>',
     '        <lifespanDays>0.5</lifespanDays>'),
    ('X8 plik klockow poza lista walidatora', '{WALIDATOR}/Program.cs',
     '        @"D:\\Games\\RimWorld\\Mods\\ProceduralNarrator\\Defs\\Blocks\\Blocks_Extended.xml",\n',
     ''),
    # ---- krok 7, S1 (2026-09-24): rdzen stylu gracza - kolejka, agregacja, skala, profil, etykiety, kierunek ----
    ('G1 FIFO wypycha najnowszy dzien zamiast najstarszego', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                Days.RemoveAt(0);',
     '                Days.RemoveAt(Days.Count - 1);'),
    ('G2 pojemnosc kolejki o jeden za duza', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            int cap = capacityDays < 1 ? 1 : capacityDays;',
     '            int cap = capacityDays < 1 ? 1 : capacityDays + 1;'),
    ('G3 rozgrzewka > zamiast >=', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '            r.Active = dni >= p.warmupDays;',
     '            r.Active = dni > p.warmupDays;'),
    ('G4 dzien 0/0 liczony jako zero w pomiarze stanu', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                    if (d.Den[i] > 0)\n                    {\n                        suma += d.Num[i] / (double)d.Den[i];\n                        n++;\n                    }',
     '                    if (d.Den[i] > 0)\n                    {\n                        suma += d.Num[i] / (double)d.Den[i];\n                    }\n                    n++;'),
    ('G5 pomiary zdarzen jako srednia z dni', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '            if (StyleSignals.Mode(s) == StyleAggregation.DailyRatioMean)',
     '            if (true)'),
    ('G6 minEvents ignorowany (Reaktywnosc z 1 epizodu)', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '            known = sumaMian >= min && sumaLicz >= sp.minNumerator;',
     '            known = sumaMian >= 1 && sumaLicz >= sp.minNumerator;'),
    ('G8 rozpietosc ignorowana w skali', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '            return Curves.Clamp01(0.5f + 0.5f * (x - sp.norm) / spread);',
     '            return Curves.Clamp01(0.5f + 0.5f * (x - sp.norm));'),
    ('G9 skala bez klamry 0..1', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '            return Curves.Clamp01(0.5f + 0.5f * (x - sp.norm) / spread);',
     '            return 0.5f + 0.5f * (x - sp.norm) / spread;'),
    ('G10 nieznany pomiar wchodzi do cechy', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                    if ((int)StyleSignals.Dimension(s) != d || !r.SignalKnown[i])',
     '                    if ((int)StyleSignals.Dimension(s) != d)'),
    ('G11 wagi pomiarow ignorowane', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                    float w = p.Signal(s).weight;',
     '                    float w = 1f;'),
    ('G12 profil wzgledny bez odjecia sredniej', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                    ? Curves.ClampSigned((r.Z[d] - srednia) / p.relativeScale)',
     '                    ? Curves.ClampSigned(r.Z[d] / p.relativeScale)'),
    ('G13 srednia profilu takze po nieznanych cechach', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                if (r.Known[d])\n                {\n                    znane++;',
     '                if (!float.IsNaN(r.Z[d]))\n                {\n                    znane++;'),
    ('G14 profil wzgledny bez klamry -1..1', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                    ? Curves.ClampSigned((r.Z[d] - srednia) / p.relativeScale)',
     '                    ? ((r.Z[d] - srednia) / p.relativeScale)'),
    ('G15 mocna strona > zamiast >=', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                r.Strong[d] = r.Known[d] && znane >= 2 && r.C[d] >= p.strongSideThreshold;',
     '                r.Strong[d] = r.Known[d] && znane >= 2 && r.C[d] > p.strongSideThreshold;'),
    ('G16 remis etykiet wygrywa pozniejszy prototyp', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                if (dist < best)',
     '                if (dist <= best)'),
    ('G17 nieznane cechy w odleglosci etykiety', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '                    if (!r.Known[d]) continue;',
     '                    ;'),
    ('G18 wagi orientacji i rytmu zamienione', '{SRC}Core/PlayerModel/StyleDirection.cs',
     '            return Curves.ClampSigned(p.orientationWeight * o + p.rhythmWeight * Rhythm(intent));',
     '            return Curves.ClampSigned(p.rhythmWeight * o + p.orientationWeight * Rhythm(intent));'),
    ('G19 utrzymanie liczone jak oddech', '{SRC}Core/PlayerModel/StyleDirection.cs',
     '                case Intent.Hold: return 0f;',
     '                case Intent.Hold: return 1f;'),
    ('G19b oddech ze znakiem eskalacji', '{SRC}Core/PlayerModel/StyleDirection.cs',
     '                default: return 1f;',
     '                default: return -1f;'),
    ('G21 profil awaryjny z orientacja Powsciagliwego', '{SRC}Core/Tension/NarratorProfile.cs',
     '        public const float FallbackStyleOrientation = 0f;',
     '        public const float FallbackStyleOrientation = 1f;'),
    ('GA Sanitize stylu nic nie robi', '{SRC}Core/PlayerModel/PlayerStyleParams.cs',
     '            var popr = new List<string>();\n\n            if (capacityDays < 1)',
     '            var popr = new List<string>();\n            return string.Empty;\n\n            if (capacityDays < 1)'),
    ('GB rozgrzewka dluzsza niz kolejka przepuszczona', '{SRC}Core/PlayerModel/PlayerStyleParams.cs',
     '            if (warmupDays > capacityDays)',
     '            if (false)'),
    ('GC postac kanoniczna z przecinkiem', '{SRC}Core/PlayerModel/StyleDimension.cs',
     "                    sb.Append(Names[i]).Append(';');",
     "                    sb.Append(Names[i]).Append(',');"),
    ('GK1 kodek D zamienia licznik z mianownikiem', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                wynik.Num[i] = n;\n                wynik.Den[i] = d;',
     '                wynik.Num[i] = d;\n                wynik.Den[i] = n;'),
    ('GK2 zapis gubi dzien w toku (linia A)', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                l.Add(EncodeDay("A", Partial));',
     '                ;'),
    ('GK3 dekoder przyjmuje drugi naglowek N', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    if (bylN || f.Length != 6 || !TI(f[1], out ver)',
     '                    if (f.Length != 6 || !TI(f[1], out ver)'),
    ('GK4 dekoder przyjmuje powtorzony albo cofniety dzien', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    if (Days.Count > 0 && s.Day <= Days[Days.Count - 1].Day)',
     '                    if (false)'),
    ('GK5 dekoder przyjmuje drugi dzien w toku', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                        if (Partial != null)\n                        {\n                            return false;\n                        }\n                        Partial = s;',
     '                        Partial = s;'),
    # ---- krok 7, S1: tresc - blok <playerStyle> i orientacje profili ----
    ('X15 Powsciagliwy z orientacja 0', '{DEFS}Storytellers/Profiles_Core.xml',
     '    <styleOrientation>1</styleOrientation>',
     '    <styleOrientation>0</styleOrientation>'),
    ('X16 rozpietosc Obrony 0', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '<li><signal>Obrona</signal><weight>1</weight><norm>0.04</norm><spread>0.04</spread>',
     '<li><signal>Obrona</signal><weight>1</weight><norm>0.04</norm><spread>0</spread>'),
    ('X17 usuniety prototyp Zaangazowany', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '            <li><label>Zaangazowany</label><walka>0.75</walka><gospodarka>0.75</gospodarka><ekspansja>0.75</ekspansja><reaktywnosc>0.75</reaktywnosc></li>\n',
     ''),
    ('X18 styl gracza wylaczony w XML', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '        <playerStyle>\n          <enabled>true</enabled>',
     '        <playerStyle>\n          <enabled>false</enabled>'),
    ('X22 Inicjatywa z waga 0 (decyzja nr 19)', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '<li><signal>Inicjatywa</signal><weight>0.5</weight>',
     '<li><signal>Inicjatywa</signal><weight>0</weight>'),
    ('X23 usuniety prototyp dwucechowy Opiekun', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '            <li><label>Opiekun</label><walka>0.5</walka><gospodarka>0.5</gospodarka><ekspansja>0.8</ekspansja><reaktywnosc>0.8</reaktywnosc></li>\n',
     ''),
    ('X24 Poborowi znany po 1 epizodzie', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '<spread>0.4</spread><minEvents>2</minEvents></li>\n            <li><signal>Szybkosc</signal>',
     '<spread>0.4</spread><minEvents>1</minEvents></li>\n            <li><signal>Szybkosc</signal>'),
    ('X25 rozgrzewka 10 dni', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '          <warmupDays>15</warmupDays>',
     '          <warmupDays>10</warmupDays>'),
    # ---- krok 7, S2 (2026-09-24): obserwacja - bazy rekordow, epizody, oferty, dzicy ludzie, ataki; kodek B/E/O/W ----
    ('G22 delta rekordow liczona od zera bez bazy', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                PawnBaseline b;\n                if (Baselines.TryGetValue(ps.Id, out b))\n                {',
     '                PawnBaseline b;\n                if (!Baselines.TryGetValue(ps.Id, out b)) b = new PawnBaseline();\n                {'),
    ('G23 delta dla pionka, ktory przestal byc kolonista', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                if (ps == null || !ps.Eligible || aktualne.ContainsKey(ps.Id))',
     '                if (ps == null || aktualne.ContainsKey(ps.Id))'),
    ('G24 ujemna delta rekordu nie scinana', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            return d < 0 ? 0 : d;',
     '            return d;'),
    ('G25 epizod zamykany pierwsza cicha probka', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    if (ep.QuietSamples >= p.quietSamplesToClose)',
     '                    if (ep.QuietSamples >= 1)'),
    ('G26 krotki epizod (migotanie) liczony', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            if (ep.ThreatSamples < p.minEpisodeSamples || ep.EligibleSum <= 0)',
     '            if (ep.EligibleSum <= 0)'),
    ('G27 szybkosc bez opoznienia poboru', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                long opoznienie = ep.FirstDraftTick - ep.StartTick;',
     '                long opoznienie = 0;'),
    ('G28 udzial poborowych na probke zamiast na zdolnych', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            long pobor = (long)Math.Round(1000.0 * ep.DraftedSum / ep.EligibleSum, MidpointRounding.AwayFromZero);',
     '            long pobor = (long)Math.Round(1000.0 * ep.DraftedSum / ep.ThreatSamples, MidpointRounding.AwayFromZero);'),
    ('G28b pierwszy pobor nadpisywany kazdym kolejnym', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    if (s.Drafted > 0 && ep.FirstDraftTick < 0)',
     '                    if (s.Drafted > 0)'),
    ('G29 przyjeta oferta zostaje oczekujaca (liczona ponownie)', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    case OfferState.Success:\n                        przyjete++;\n                        rozstrzygniete++;\n                        PendingOffers.Remove(o.Id);',
     '                    case OfferState.Success:\n                        przyjete++;\n                        rozstrzygniete++;'),
    ('G30 znak wodny zadan ignorowany', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                else if (!PendingOffers.Contains(o.Id))\n                {\n                    continue;\n                }',
     ''),
    ('G31 odrzucona oferta liczona jako przyjeta', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    case OfferState.Fail:\n                        rozstrzygniete++;',
     '                    case OfferState.Fail:\n                        przyjete++;\n                        rozstrzygniete++;'),
    ('G32 limit dni dzikusa ignorowany', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                         || (st == WildManStatus.Wild && dzien.Day - kv.Value >= p.wildManTimeoutDays))',
     '                         || false)'),
    ('G33 atak liczony przy kazdej probce', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            if (lastTickPlayerRaidedSomeone > LastRaidTick)',
     '            if (lastTickPlayerRaidedSomeone >= LastRaidTick)'),
    ('GI1 Initialize nie sledzi ofert w toku', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    if (o.State == OfferState.Pending) PendingOffers.Add(o.Id);',
     '                    ;'),
    ('GI2 Initialize daje baze nie-koloniscie', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    if (ps != null && ps.Eligible)\n                    {\n                        Baselines[ps.Id] = Baza(ps);',
     '                    if (ps != null)\n                    {\n                        Baselines[ps.Id] = Baza(ps);'),
    ('GI3 znikniety dzikus nie jest odrzuceniem', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    st = WildManStatus.Gone;',
     '                    st = WildManStatus.Wild;'),
    ('GI4 epizod zamknietej mapy liczony', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            foreach (int map in zniknete)\n            {\n                Episodes.Remove(map);\n            }',
     '            foreach (int map in zniknete)\n            {\n                CloseEpisode(Episodes[map], p);\n                Episodes.Remove(map);\n            }'),
    ('GK6 kodek B zamienia produktywne z pomocniczymi', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                l.Add(Join("B", I(kv.Key), L(b.Productive), L(b.Support), L(b.Recruited), L(b.Captured)));',
     '                l.Add(Join("B", I(kv.Key), L(b.Support), L(b.Productive), L(b.Recruited), L(b.Captured)));'),
    ('GK7 kodek E gubi tick pierwszego poboru', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                           L(e.FirstDraftTick), I(e.QuietSamples), e.Capped ? "1" : "0"));',
     '                           L(-1), I(e.QuietSamples), e.Capped ? "1" : "0"));'),
    ('GK8 zapis gubi oferty oczekujace (linie O)', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                l.Add(Join("O", I(q)));',
     '                ;'),
    ('GK9 zapis gubi dzikich ludzi (linie W)', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                l.Add(Join("W", I(kv.Key), I(kv.Value)));',
     '                ;'),
    ('GK10 dekoder przyjmuje zdublowana baze', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '|| !TL(f[4], out r) || !TL(f[5], out c) || Baselines.ContainsKey(id))',
     '|| !TL(f[4], out r) || !TL(f[5], out c))'),
    # ---- krok 7, S3 (2026-09-24): styl w decyzji - wartosc, premia C6, warunek, katalog, linia P, kolumny ----
    ('G40 Apply stylu zmienia Utility', '{SRC}Core/PlayerModel/StyleFocus.cs',
     '                k.StyleValue = ValueFor(k.Event, out why);',
     '                k.StyleValue = ValueFor(k.Event, out why);\n                k.Utility += 0.1f * k.StyleValue;'),
    ('G41 premia stylu takze poza pula pasma', '{SRC}Core/Decision/SelectionPolicy.cs',
     '            for (int i = 0; i < pulaZdarzen.Count; i++)\n            {\n                ScoredCandidate k = pulaZdarzen[i];\n                if (k.StyleApplied && k.StyleValue != 0f)',
     '            for (int i = 0; i < lista.Count; i++)\n            {\n                ScoredCandidate k = lista[i];\n                if (k.StyleApplied && k.StyleValue != 0f)'),
    ('G42 premia stylu liczona od best zamiast od szerokosci pasma', '{SRC}Core/Decision/SelectionPolicy.cs',
     '            float premiaStylu = best - progPasma;',
     '            float premiaStylu = best;'),
    ('G43 SelectionScore bez premii stylu', '{SRC}Core/Model/ScoredCandidate.cs',
     '            get { return Utility + ArcBonus + StyleBonus; }',
     '            get { return Utility + ArcBonus; }'),
    ('G44 premia stylu nie zerowana miedzy rundami', '{SRC}Core/Decision/SelectionPolicy.cs',
     '                lista[i].StyleBonus = 0f;\n',
     ''),
    ('G45 dopasowanie bez normalizacji suma wag', '{SRC}Core/PlayerModel/StyleFocus.cs',
     '            return sumaW > 0.0 ? Curves.ClampSigned((float)(sumaWC / sumaW)) : 0f;',
     '            return sumaW > 0.0 ? Curves.ClampSigned((float)sumaWC) : 0f;'),
    ('G46 wagi stylu z kazdego klocka, nie tylko akcji', '{SRC}Core/PlayerModel/StyleFocus.cs',
     '                if (b != null && b.Type == BlockType.Action)',
     '                if (b != null)'),
    ('G47 nieznane cechy w dopasowaniu', '{SRC}Core/PlayerModel/StyleFocus.cs',
     '                if (!Reading.Known[d] || !(w > 0f))',
     '                if (!(w > 0f))'),
    ('G48 kierunek d ignorowany (v = a)', '{SRC}Core/PlayerModel/StyleFocus.cs',
     '            float v = Curves.ClampSigned(Direction * a);',
     '            float v = Curves.ClampSigned(a);'),
    ('G49 scorer nie naklada fokusu stylu', '{SRC}Core/Decision/UtilityScorer.cs',
     '                context.StyleFocus.Apply(wynik);',
     '                ;'),
    ('G50 styl dla PASS i zawetowanych', '{SRC}Core/PlayerModel/StyleFocus.cs',
     '                if (k == null || k.IsPass || k.Vetoed || k.Event == null)',
     '                if (k == null || k.Event == null)'),
    ('G51 warunek stylu ignoruje required', '{SRC}Core/Conditions/HardConditions.cs',
     '            return jest == required;',
     '            return jest;'),
    ('G53 katalog lukow przyjmuje nieznana ceche stylu', '{SRC}Core/Arcs/ArcCatalog.cs',
     '                    if (styl != null && !PlayerModel.StyleDimensions.TryParse(styl.dimension, out cecha))',
     '                    if (false)'),
    ('G54 regresja SafeId z S6 przywrocona', '{SRC}Core/Arcs/ArcCatalog.cs',
     '            else if (!SafeId(a.defName))\n            {\n                p.Add("defName moze zawierac tylko litery, cyfry i \'_\'");\n            }\n            // Klucz faktu w warunku startu (S6)',
     '            // Klucz faktu w warunku startu (S6)'),
    ('G55 linia P nie zapamietuje stylu', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     '            HasDecisionStyle = true;\n            DecisionStyleStrongSides = decyzji.StyleStrongSides ?? string.Empty;',
     '            HasDecisionStyle = false;'),
    ('G56 nakladka sciezki spoznionej bez stylu', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     '                spozniony.StyleStrongSides = DecisionStyleStrongSides ?? string.Empty;',
     '                ;'),
    ('G57 kodek P odrzuca linie 18 pol (S6)', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     '            if ((f.Length != FieldCount && f.Length != S6FieldCount && f.Length != LegacyFieldCount) || f[0] != LineTag)',
     '            if ((f.Length != FieldCount && f.Length != LegacyFieldCount) || f[0] != LineTag)'),
    ('G57b kodek P przyjmuje znieksztalcone pole stylu', '{SRC}Core/Arcs/ExecutionConfirmation.cs',
     "                else if (f[18].Length > 2 && f[18][0] == ';' && f[18][f[18].Length - 1] == ';')",
     '                else if (true)'),
    ('G58 Kopia() bez mocnych stron stylu', '{WALIDATOR}/Program.cs',
     '            Threads = s.Threads, Facts = s.Facts, TurnsSinceThemes = s.TurnsSinceThemes,\n            // Mocne strony stylu gracza (krok 7).\n            StyleStrongSides = s.StyleStrongSides',
     '            Threads = s.Threads, Facts = s.Facts, TurnsSinceThemes = s.TurnsSinceThemes'),
    ('G59 kolumny cech wypelnione w rozgrzewce', '{SRC}Core/PlayerModel/StyleFocus.cs',
     '                c.Z[d] = r != null && r.Active && r.Known[d] ? F(r.Z[d]) : string.Empty;',
     '                c.Z[d] = r != null && !float.IsNaN(r.Z[d]) ? F(r.Z[d]) : string.Empty;'),
    ('G59b stylWPasmie liczy wszystkich w pasmie', '{SRC}Core/Decision/SelectionPolicy.cs',
     '                StyleNonZeroInBand = stylStosowany ? stylowychWPasmie : -1,',
     '                StyleNonZeroInBand = stylStosowany ? pulaZdarzen.Count : -1,'),
    ('G60 fokus stylu z intencji przed kryzysem', '{SRC}Core/Tension/TurnPlanner.cs',
     '                : StyleFocus.Build(style, styleOrientation, plan.Intent.Intent, styleParams);',
     '                : StyleFocus.Build(style, styleOrientation, IntentSelector.Select(plan.Tension.Tension, tensionModel.Parameters).Intent, styleParams);'),
    ('G61 styl bez zgodnosci ladunku z krzywa', '{SRC}Core/PlayerModel/StyleFocus.cs',
     '            if (!ArcIntentRules.Compatible(e.Valence, Intent))',
     '            if (false)'),
    ('G62 ogon danych wypelniony bez stylu', '{SRC}Core/Decision/NarratorDecision.cs',
     '            bool stylowy = !pass && w != null && w.StyleApplied;',
     '            bool stylowy = !pass && w != null;'),
    # ---- krok 7, S3: tresc - wagi stylu akcji, warunek stylu poza lukami ----
    ('X11 Napad bez wag stylu', '{DEFS}Blocks/Blocks_Core.xml',
     '    <styleWeights><walka>1</walka><reaktywnosc>0.5</reaktywnosc></styleWeights>\n    <!-- Krok 5: jedyny incydent',
     '    <!-- Krok 5: jedyny incydent'),
    ('X12 warunek stylu w warunkach klocka Napadu', '{DEFS}Blocks/Blocks_Core.xml',
     '        <text>rusza do ataku na kolonie.</text>\n      </li>\n    </textVariants>\n    <conditions>\n      <li Class="ProceduralNarrator.Core.Conditions.Cond_HostileFaction"/>',
     '        <text>rusza do ataku na kolonie.</text>\n      </li>\n    </textVariants>\n    <conditions>\n      <li Class="ProceduralNarrator.Core.Conditions.Cond_HostileFaction"/>\n      <li Class="ProceduralNarrator.Core.Conditions.Cond_StylMocnaStrona"><dimension>Walka</dimension><required>false</required></li>'),
    ('X13 Napad z waga Walki 0.5', '{DEFS}Blocks/Blocks_Core.xml',
     '    <styleWeights><walka>1</walka><reaktywnosc>0.5</reaktywnosc></styleWeights>\n    <!-- Krok 5: jedyny incydent',
     '    <styleWeights><walka>0.5</walka><reaktywnosc>0.5</reaktywnosc></styleWeights>\n    <!-- Krok 5: jedyny incydent'),
    ('X21 wagi stylu na klocku aktora', '{DEFS}Blocks/Blocks_Core.xml',
     '    <defName>PN_Aktor_Piraci</defName>\n    <blockType>Actor</blockType>',
     '    <defName>PN_Aktor_Piraci</defName>\n    <blockType>Actor</blockType>\n    <styleWeights><walka>1</walka></styleWeights>'),
    # ---- krok 7, S4 (2026-09-24): tresc - cztery luki pod styl gracza ----
    ('X9 Slawa twierdzy bez warunku stylu', '{DEFS}Arcs/Arcs_Core.xml',
     '      <li Class="ProceduralNarrator.Core.Conditions.Cond_StylMocnaStrona">\n        <dimension>Walka</dimension>\n      </li>\n',
     ''),
    ('X10 Slawa twierdzy z priorytetem nizszym niz Wendeta', '{DEFS}Arcs/Arcs_Core.xml',
     '    <defName>PN_Luk_SlawaTwierdzy</defName>\n    <label>slawa twierdzy</label>\n    <priority>12</priority>',
     '    <defName>PN_Luk_SlawaTwierdzy</defName>\n    <label>slawa twierdzy</label>\n    <priority>9</priority>'),
    ('X14 Niespokojne noce z dluga eskalacja', '{DEFS}Arcs/Arcs_Core.xml',
     '        <minDaysAfterPrevious>1</minDaysAfterPrevious>\n        <maxDays>8</maxDays>\n        <expectations>\n          <li>\n            <themes><li>Natural</li></themes>',
     '        <minDaysAfterPrevious>1</minDaysAfterPrevious>\n        <maxDays>20</maxDays>\n        <expectations>\n          <li>\n            <themes><li>Natural</li></themes>'),
    ('X19 Dostatek - kulminacja bez przejscia strat', '{DEFS}Arcs/Arcs_Core.xml',
     '        <message>Tym razem kolonii zagrazaja napastnicy.</message>\n        <messageType>NegativeEvent</messageType>\n        <transitions>\n          <li>\n            <guards>\n              <li Class="ProceduralNarrator.Core.Arcs.Guard_ColonistsLost">\n                <min>1</min>\n              </li>\n            </guards>\n            <target>Rozwiazanie</target>\n            <message>Kolonia liczy straty.</message>\n          </li>\n        </transitions>\n',
     '        <message>Tym razem kolonii zagrazaja napastnicy.</message>\n        <messageType>NegativeEvent</messageType>\n'),
    ('X20 Dostatek bez wrogiej frakcji', '{DEFS}Arcs/Arcs_Core.xml',
     '    <exclusionGroup>niebo</exclusionGroup>\n    <cooldownDays>30</cooldownDays>\n    <startConditions>\n      <li Class="ProceduralNarrator.Core.Conditions.Cond_HostileFaction"/>\n',
     '    <exclusionGroup>niebo</exclusionGroup>\n    <cooldownDays>30</cooldownDays>\n    <startConditions>\n'),
    ('X26 zmieniony zatwierdzony tekst Ziemi obiecanej', '{DEFS}Arcs/Arcs_Core.xml',
     '<message>Po przybyszach przychodza klopoty.</message>',
     '<message>Za przybyszami przychodza klopoty.</message>'),
    # ---- krok 7, S5 (2026-09-24): opis luku do [PN-CONFIG] z warunkiem stylu ----
    ('G63 opis luku bez warunku stylu', '{SRC}Core/Arcs/ArcCatalog.cs',
     '                   + "; warunekStylu=" + WarunekStylu(a);',
     '                   + "; warunekStylu=-";'),
    ('G64 opis luku gubi required=false', '{SRC}Core/Arcs/ArcCatalog.cs',
     '                .Select(c => (c.required ? string.Empty : "!") + (c.dimension ?? "?"))',
     '                .Select(c => string.Empty + (c.dimension ?? "?"))'),
    # ---- krok 7, S8 (2026-09-24): poprawki po przegladzie adwersarialnym (decyzje autora + czyste bledy) ----
    ('G65 Inicjatywa bez progu licznika', '{SRC}Core/PlayerModel/PlayerStyleModel.cs',
     '            known = sumaMian >= min && sumaLicz >= sp.minNumerator;',
     '            known = sumaMian >= min;'),
    ('G66 limit dlugosci epizodu wylaczony', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                    if (tick - ep.StartTick >= p.maxEpisodeTicks)',
     '                    if (false)'),
    ('G67 epizod po limicie liczony drugi raz przy ciszy', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                        if (!ep.Capped)\n                        {\n                            CloseEpisode(ep, p);',
     '                        if (true)\n                        {\n                            CloseEpisode(ep, p);'),
    ('G68 blokada po limicie dalej zbiera probki', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                if (s.Threat && ep != null && ep.Capped)',
     '                if (false)'),
    ('G69 znak wodny ofert zalezny od kolejnosci', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '                bool nowa = o.Id > znakWodny;',
     '                bool nowa = o.Id > MaxOfferId;'),
    ('G70 limit dzikusa o dobe za wczesnie', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '(st == WildManStatus.Wild && dzien.Day - kv.Value >= p.wildManTimeoutDays)',
     '(st == WildManStatus.Wild && dzien.Day + 1 - kv.Value >= p.wildManTimeoutDays)'),
    ('G71 brak odbudowy dnia w toku po wczytaniu', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            if (Initialized && Partial == null)',
     '            if (false)'),
    ('G72 kodek E gubi flage limitu', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     'I(e.QuietSamples), e.Capped ? "1" : "0"));',
     'I(e.QuietSamples), "0"));'),
    ('G73 luk bez pierwszenstwa przed ujemna premia stylu', '{SRC}Core/Decision/SelectionPolicy.cs',
     '                    k.StyleBonus = k.ArcBonus > 0f && k.StyleValue < 0f ? 0f : premiaStylu * k.StyleValue;',
     '                    k.StyleBonus = premiaStylu * k.StyleValue;'),
    ('G74 luk tlumi takze dodatnia premie stylu', '{SRC}Core/Decision/SelectionPolicy.cs',
     '                    k.StyleBonus = k.ArcBonus > 0f && k.StyleValue < 0f ? 0f : premiaStylu * k.StyleValue;',
     '                    k.StyleBonus = k.ArcBonus > 0f ? 0f : premiaStylu * k.StyleValue;'),
    ('G75 Szybkosc bez skali promili', '{SRC}Core/PlayerModel/StyleSignal.cs',
     '        private static readonly int[] Scales = { 1, 1, 1, 1, 1, 1, 1000, 1000 };',
     '        private static readonly int[] Scales = { 1, 1, 1, 1, 1, 1, 1000, 1 };'),
    ('G76 Szybkosc przypisana Walce', '{SRC}Core/PlayerModel/StyleSignal.cs',
     '            StyleDimension.Reaktywnosc, StyleDimension.Reaktywnosc\n        };',
     '            StyleDimension.Reaktywnosc, StyleDimension.Walka\n        };'),
    ('G77 Praca w trybie sum', '{SRC}Core/PlayerModel/StyleSignal.cs',
     '            StyleAggregation.DailyRatioMean, StyleAggregation.DailyRatioMean,\n            StyleAggregation.RatioOfSums, StyleAggregation.RatioOfSums,\n            StyleAggregation.RatioOfSums, StyleAggregation.RatioOfSums\n        };',
     '            StyleAggregation.RatioOfSums, StyleAggregation.DailyRatioMean,\n            StyleAggregation.RatioOfSums, StyleAggregation.RatioOfSums,\n            StyleAggregation.RatioOfSums, StyleAggregation.RatioOfSums\n        };'),
    ('G78 epizod bez zdolnych do walki liczony', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            if (ep.ThreatSamples < p.minEpisodeSamples || ep.EligibleSum <= 0)',
     '            if (ep.ThreatSamples < p.minEpisodeSamples)'),
    ('G79 jeniec-dzikus z limitem dni', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '(st == WildManStatus.Wild && dzien.Day - kv.Value >= p.wildManTimeoutDays)',
     '(st != WildManStatus.Joined && dzien.Day - kv.Value >= p.wildManTimeoutDays)'),
    ('G80 atak widziany przy zamknieciu doby pominiety', '{SRC}Core/PlayerModel/PlayerStyleLedger.cs',
     '            ObserveRaidTick(obs.LastPlayerRaidTick);\n            dzien.Add(StyleSignal.Inicjatywa, 0, 1);',
     '            dzien.Add(StyleSignal.Inicjatywa, 0, 1);'),
    # ---- krok 7, S8: tresc ----
    ('X27 Niespokojne noce - zasiew bez skali (Amok otwiera Noce)', '{DEFS}Arcs/Arcs_Core.xml',
     '            <scales><li>Moderate</li></scales>\n          </li>\n        </expectations>\n        <message>Kolonia uczy sie spac czujnie.</message>',
     '          </li>\n        </expectations>\n        <message>Kolonia uczy sie spac czujnie.</message>'),
    ('X28 Slawa - kulminacja bez progu mocy', '{DEFS}Arcs/Arcs_Core.xml',
     '            <minIntensity>High</minIntensity>\n            <requiredTag>militarny</requiredTag>',
     '            <requiredTag>militarny</requiredTag>'),
    ('X29 Dostatek z powrotem we wlasnej grupie', '{DEFS}Arcs/Arcs_Core.xml',
     '    <priority>6</priority>\n    <exclusionGroup>niebo</exclusionGroup>',
     '    <priority>6</priority>\n    <exclusionGroup>dobytek</exclusionGroup>'),
    ('X30 tekst Dostatku znow z "ludzie"', '{DEFS}Arcs/Arcs_Core.xml',
     '<message>Tym razem kolonii zagrazaja napastnicy.</message>',
     '<message>Tym razem kolonii zagrazaja ludzie.</message>'),
    ('X31 superlatyw Slawy wraca', '{DEFS}Arcs/Arcs_Core.xml',
     '<message>Obroncow kolonii czeka ciezka proba.</message>',
     '<message>Nadchodzi najciezsza proba dla obroncow kolonii.</message>'),
    ('X32 Przyjecia znane od jednej oferty', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '<signal>Przyjecia</signal><weight>1</weight><norm>0.5</norm><spread>0.5</spread><minEvents>3</minEvents>',
     '<signal>Przyjecia</signal><weight>1</weight><norm>0.5</norm><spread>0.5</spread><minEvents>1</minEvents>'),
    ('X33 Inicjatywa bez progu licznika w XML', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '<minEvents>1</minEvents><minNumerator>1</minNumerator>',
     '<minEvents>1</minEvents>'),
    ('X34 bez oferty z Royalty', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '            <li MayRequire="Ludeon.RimWorld.Royalty">WandererJoinAbasia</li>\n',
     ''),
    ('X35 Werbunek znany od jednego jenca', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '<signal>Werbunek</signal><weight>0.5</weight><norm>0.3</norm><spread>0.3</spread><minEvents>2</minEvents>',
     '<signal>Werbunek</signal><weight>0.5</weight><norm>0.3</norm><spread>0.3</spread><minEvents>1</minEvents>'),
    # ---- krok 8, czesc moda (2026-09-25) - S1: ExecutionSpec (dlug 9) ----
    ('E1 klucz wykonania bez frakcji', '{SRC}Core/Model/ExecutionSpec.cs',
     '                       + (FactionId == null ? string.Empty : "|F" + FactionId);',
     '                       + string.Empty;'),
    ('E2 klucz wykonania bez mocy', '{SRC}Core/Model/ExecutionSpec.cs',
     '                return (Payload ?? "?") + "|"\n                       + ((int)Intensity).ToString(CultureInfo.InvariantCulture)',
     '                return (Payload ?? "?") + "|"\n                       + string.Empty'),
    ('E3 specyfikacja gubi frakcje luku', '{SRC}Core/Model/ExecutionSpec.cs',
     '            return new ExecutionSpec(zdarzenie.ActionPayload, zdarzenie.Intensity, factionId);',
     '            return new ExecutionSpec(zdarzenie.ActionPayload, zdarzenie.Intensity, null);'),
    ('E4 pusta frakcja nie jest brakiem frakcji', '{SRC}Core/Model/ExecutionSpec.cs',
     '            FactionId = string.IsNullOrEmpty(factionId) ? null : factionId;',
     '            FactionId = factionId;'),
    # ---- krok 8, S2: warianty tekstu (K8-6) ----
    ('T1 wariant dopasowany bez pierwszenstwa', '{SRC}Core/Composition/TextComposer.cs',
     '            if (dopasowane.Count > 0)\n            {\n                indeks = Indeks(ziarno, klocek.Id, dopasowane.Count);',
     '            if (false)\n            {\n                indeks = Indeks(ziarno, klocek.Id, dopasowane.Count);'),
    ('T2 wariant ignoruje warunki swiata', '{SRC}Core/Model/TextVariant.cs',
     '                    if (conditions[i] == null || !conditions[i].IsMet(snapshot))',
     '                    if (conditions[i] == null)'),
    ('T3 brak snapshotu = warunki spelnione', '{SRC}Core/Model/TextVariant.cs',
     '                if (snapshot == null)\n                {\n                    return false;\n                }',
     '                if (snapshot == null)\n                {\n                    return true;\n                }'),
    ('T4 wariant ignoruje moc koncowa', '{SRC}Core/Model/TextVariant.cs',
     '            if (mocKoncowa < minIntensity || mocKoncowa > maxIntensity)',
     '            if (false)'),
    ('T5 wariant ignoruje skalowanie punktami', '{SRC}Core/Model/TextVariant.cs',
     '            if (requiresPointsScaling && !akcjaSkalujeSie)',
     '            if (false)'),
    ('T6 wariant frakcyjny bez znanej frakcji', '{SRC}Core/Model/TextVariant.cs',
     '            if (requiresFaction && string.IsNullOrEmpty(nazwaFrakcji))',
     '            if (false)'),
    ('T7 znacznik frakcji nie zastapiony', '{SRC}Core/Composition/TextComposer.cs',
     '            return v.requiresFaction ? v.text.Replace(FactionPlaceholder, nazwaFrakcji ?? string.Empty) : v.text;',
     '            return v.text;'),
    ('T8 warunek miekki uznany za twardy', '{SRC}Core/Composition/TextComposer.cs',
     '            return m != null && m.DeclaringType != typeof(NarrativeCondition)\n                   && m.GetBaseDefinition()',
     '            return m != null\n                   && m.GetBaseDefinition()'),
    ('T9 znacznik bez requiresFaction przepuszczony', '{SRC}Core/Composition/TextComposer.cs',
     '            if (maZnacznik && !v.requiresFaction)',
     '            if (false)'),
    ('T10 zdublowane id przepuszczone', '{SRC}Core/Composition/TextComposer.cs',
     '            if (zajeteId != null && zajeteId.Contains(v.id))',
     '            if (false)'),
    ('T11 wybor bez ziarna (zawsze pierwszy)', '{SRC}Core/Composition/TextComposer.cs',
     '            if (rozmiar <= 1)\n            {\n                return 0;\n            }',
     '            if (true)\n            {\n                return 0;\n            }'),
    ('T12 Compose nie widzi skalowania akcji', '{SRC}Core/Composition/TextComposer.cs',
     '                    akcjaSkalujeSie = b.ScalesWithPoints;',
     '                    akcjaSkalujeSie = false;'),
    ('T13 nieznany nawias przepuszczony', '{SRC}Core/Composition/TextComposer.cs',
     "            if (bezZnacznika.IndexOf('{') >= 0 || bezZnacznika.IndexOf('}') >= 0)",
     '            if (false)'),
    ('X36 Napad bez scalesWithPoints', '{DEFS}Blocks/Blocks_Core.xml',
     '    <payload>RaidEnemy</payload>\n    <scalesWithPoints>true</scalesWithPoints>\n',
     '    <payload>RaidEnemy</payload>\n'),
    ('X37 Zrzut deklaruje scalesWithPoints', '{DEFS}Blocks/Blocks_Core.xml',
     '    <payload>ResourcePodCrash</payload>\n',
     '    <payload>ResourcePodCrash</payload>\n    <scalesWithPoints>true</scalesWithPoints>\n'),
    # ---- krok 8, S3: list gracza (K8-4) ----
    # ---- krok 8, S10: przeglad adwersarialny - warianty tekstu ----
    ('T14 przesloniecie new uznane za nadpisanie', '{SRC}Core/Composition/TextComposer.cs',
     '            return m != null && m.DeclaringType != typeof(NarrativeCondition)\n                   && m.GetBaseDefinition().DeclaringType == typeof(NarrativeCondition);',
     '            return m != null && m.DeclaringType != typeof(NarrativeCondition);'),
    ('T15 id wariantu tylko bez przecinka i dwukropka', '{SRC}Core/Composition/TextComposer.cs',
     '                if (!dozwolony)',
     "                if (!dozwolony && (c == ',' || c == ':'))"),
    ('T16 indeks z string.GetHashCode', '{SRC}Core/Composition/TextComposer.cs',
     '                int mieszane = SeededRandom.Avalanche(ziarno ^ (StableHash(idKlocka) * 16777619));',
     '                int mieszane = SeededRandom.Avalanche(ziarno ^ (idKlocka.GetHashCode() * 16777619));'),
    ('T17 indeks bez id klocka', '{SRC}Core/Composition/TextComposer.cs',
     '                int mieszane = SeededRandom.Avalanche(ziarno ^ (StableHash(idKlocka) * 16777619));',
     '                int mieszane = SeededRandom.Avalanche(ziarno);'),
    ('T18 skalowanie nie czyni wariantu dopasowanym', '{SRC}Core/Model/TextVariant.cs',
     '                       || requiresPointsScaling\n                       || requiresFaction;',
     '                       || requiresFaction;'),
    ('T19 frakcja nie czyni wariantu dopasowanym', '{SRC}Core/Model/TextVariant.cs',
     '                       || requiresPointsScaling\n                       || requiresFaction;',
     '                       || requiresPointsScaling;'),
    ('T20 maxIntensity nie czyni wariantu dopasowanym', '{SRC}Core/Model/TextVariant.cs',
     '                       || maxIntensity != IntensityLevel.VeryHigh\n',
     ''),
    ('T21 minIntensity nie czyni wariantu dopasowanym', '{SRC}Core/Model/TextVariant.cs',
     '                       || minIntensity != IntensityLevel.VeryLow\n',
     ''),
    ('T22 Matches ignoruje minIntensity', '{SRC}Core/Model/TextVariant.cs',
     '            if (mocKoncowa < minIntensity || mocKoncowa > maxIntensity)',
     '            if (mocKoncowa > maxIntensity)'),
    ('T23 Matches ignoruje maxIntensity', '{SRC}Core/Model/TextVariant.cs',
     '            if (mocKoncowa < minIntensity || mocKoncowa > maxIntensity)',
     '            if (mocKoncowa < minIntensity)'),
    ('T24 FNV z zerowa baza przesuniecia', '{SRC}Core/Composition/TextComposer.cs',
     '                uint h = 2166136261;',
     '                uint h = 0;'),
    ('X38 zlozony list wylaczony w XML', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '        <useComposedLetter>true</useComposedLetter>',
     '        <useComposedLetter>false</useComposedLetter>'),
    # ---- krok 8, S4: detektor odpalen [PN-FIRED] (K8-2) ----
    ('F1 odpalenie na granicy przegladu powtorzone', '{SRC}Core/Evaluation/FireDetector.cs',
     '                    if (kv.Value > prog)',
     '                    if (kv.Value >= prog)'),
    ('F2 wpis z przyszlosci wykryty', '{SRC}Core/Evaluation/FireDetector.cs',
     '                    if (kv.Value > now)\n                    {\n                        if (!znany',
     '                    if (false)\n                    {\n                        if (!znany'),
    ('F3 znacznik celu nie przesuwany', '{SRC}Core/Evaluation/FireDetector.cs',
     '            ostatniPrzeglad[cel] = Math.Max(prog, now);',
     '            ostatniPrzeglad[cel] = prog;'),
    ('F4 znacznik celu cofa sie z zegarem', '{SRC}Core/Evaluation/FireDetector.cs',
     '            ostatniPrzeglad[cel] = Math.Max(prog, now);',
     '            ostatniPrzeglad[cel] = now;'),
    ('F5 nowy cel od ticku zero zamiast startu', '{SRC}Core/Evaluation/FireDetector.cs',
     '            return cel != null && ostatniPrzeglad.TryGetValue(cel, out t) ? t : StartTick;',
     '            return cel != null && ostatniPrzeglad.TryGetValue(cel, out t) ? t : 0;'),
    ('F6 wykryte bez sortowania', '{SRC}Core/Evaluation/FireDetector.cs',
     '            if (wynik.Count - start > 1)',
     '            if (false)'),
    # ---- krok 8, S10: detektor po przegladzie (kopie StoryState, fantomy) ----
    ('F7 nowy cel zawsze od startu detektora', '{SRC}Core/Evaluation/FireDetector.cs',
     '                prog = now == pierwszyPrzeglad ? StartTick : now;',
     '                prog = StartTick;'),
    ('F8 fantom niezapamietany', '{SRC}Core/Evaluation/FireDetector.cs',
     '                            fantomy[klucz] = kv.Value;\n                            noweFantomy++;',
     '                            noweFantomy++;'),
    ('F9 fantom zawsze pomijany (nadpisanie zgubione)', '{SRC}Core/Evaluation/FireDetector.cs',
     '                        if (fantom == kv.Value)',
     '                        if (true)'),
    ('F10 cykl pierwszego przegladu nieustalony', '{SRC}Core/Evaluation/FireDetector.cs',
     '                pierwszyPrzeglad = now;',
     '                pierwszyPrzeglad = -2;'),
    # ---- krok 8, S6: izolacja cache'u CanFireNow (dlug 8, K8-3) ----
    ('H1 pytanie bez uniewaznienia cache', '{SRC}Core/Decision/VerdictCacheGuard.cs',
     '            return new VerdictCacheState(InvalidTick, false);\n        }\n\n        /// <summary>\n        /// Koniec naszej tury',
     '            return obecny;\n        }\n\n        /// <summary>\n        /// Koniec naszej tury'),
    ('H2 kolizja nigdy niewykrywana', '{SRC}Core/Decision/VerdictCacheGuard.cs',
     '                kolizja = obecny.Tick == now;',
     '                kolizja = false;'),
    ('H3 stan cache nieprzywracany', '{SRC}Core/Decision/VerdictCacheGuard.cs',
     '                wynik.Add(new KeyValuePair<string, VerdictCacheState>(kolejnosc[i], oryginaly[kolejnosc[i]]));',
     '                continue;'),
    ('H4 drugie pytanie nadpisuje oryginal', '{SRC}Core/Decision/VerdictCacheGuard.cs',
     '            if (klucz != null && !oryginaly.ContainsKey(klucz))',
     '            if (klucz != null)'),
    # ---- krok 8, S10: straz cache'u po przegladzie (tick tury) ----
    ('H5 EndTurn nie czysci strazy', '{SRC}Core/Decision/VerdictCacheGuard.cs',
     '            }\n            Discard();\n            return wynik;',
     '            }\n            return wynik;'),
    ('H6 EndTurn przywraca w innym ticku', '{SRC}Core/Decision/VerdictCacheGuard.cs',
     '            if (now == tickTury)',
     '            if (true)'),
    ('H7 resztki tury przerwanej nieporzucane', '{SRC}Core/Decision/VerdictCacheGuard.cs',
     '            if (kolejnosc.Count > 0 && tickTury != now)',
     '            if (false)'),
    # ---- krok 8, S7: drobne dlugi 6 i 12 (K8-8) ----
    ('D1 pora roku ignorowana w warunku', '{SRC}Core/Conditions/HardConditions.cs',
     '            return s.SeasonAcceptableForHumans == wantAcceptable;',
     '            return true;'),
    ('D2 porod znow liczony jako ostry', '{SRC}Core/Tension/AcuteDownedRule.cs',
     '            if (f.InPainShock && !f.InLabor)',
     '            if (f.InPainShock)'),
    ('D3 stany bez ran nieliczone', '{SRC}Core/Tension/AcuteDownedRule.cs',
     '            return lethalFraction > 0f && f.MaxLethalFraction >= lethalFraction;',
     '            return false;'),
    ('D4 prog smiertelnosci ostry zamiast nieostrego', '{SRC}Core/Tension/AcuteDownedRule.cs',
     '            return lethalFraction > 0f && f.MaxLethalFraction >= lethalFraction;',
     '            return lethalFraction > 0f && f.MaxLethalFraction > lethalFraction;'),
    ('D5 niemowle liczone jako ostre', '{SRC}Core/Tension/AcuteDownedRule.cs',
     '            if (!f.Downed || f.AlwaysDowned)',
     '            if (!f.Downed)'),
    ('D6 Clone gubi prog smiertelnosci', '{SRC}Core/Tension/CrisisDetector.cs',
     '            return new CrisisParams { downedFraction = downedFraction, minDowned = minDowned, enabled = enabled,\n                                      lethalFraction = lethalFraction };',
     '            return new CrisisParams { downedFraction = downedFraction, minDowned = minDowned, enabled = enabled };'),
    ('D7 Sanitize bez dolnej granicy progu', '{SRC}Core/Tension/CrisisDetector.cs',
     '            else if (lethalFraction < 0.05f)',
     '            else if (false)'),
    ('X39 dziki czlowiek bez warunku pory roku', '{DEFS}Blocks/Blocks_Extended.xml',
     '      <li Class="ProceduralNarrator.Core.Conditions.Cond_SeasonAcceptableForHumans" />\n',
     ''),
    # ---- krok 8, S10: skazone powietrze (dlug 6) ----
    ('D8 pora roku bez odwrocenia wantAcceptable', '{SRC}Core/Conditions/HardConditions.cs',
     '            return s.SeasonAcceptableForHumans == wantAcceptable;',
     '            return s.SeasonAcceptableForHumans;'),
    ('D9 skazone powietrze ignorowane w warunku', '{SRC}Core/Conditions/HardConditions.cs',
     '            return s.ToxicAirActive == wantToxic;',
     '            return true;'),
    ('X48 dziki czlowiek bez warunku czystego powietrza', '{DEFS}Blocks/Blocks_Extended.xml',
     '      <li Class="ProceduralNarrator.Core.Conditions.Cond_ToxicAir" />\n',
     ''),
    ('X40 prog smiertelnosci 0.9 w XML', '{DEFS}Storytellers/Storyteller_Generative.xml',
     '          <lethalFraction>0.5</lethalFraction>',
     '          <lethalFraction>0.9</lethalFraction>'),
    # ---- krok 8, S8: tresc wariantow tekstu (K8-6, zatwierdzona 2026-09-25) ----
    ('X41 zatwierdzony tekst zmieniony', '{DEFS}Blocks/Blocks_Core.xml',
     '        <text>rusza do ataku na kolonie.</text>',
     '        <text>rusza do ataku na osade.</text>'),
    ('X42 znow bez warunku faktu', '{DEFS}Blocks/Blocks_Consequences.xml',
     '          <li Class="ProceduralNarrator.Core.Conditions.Cond_Fakt"><key>wrak.lezy</key></li>\n',
     ''),
    ('X43 wariant frakcyjny bez requiresFaction', '{DEFS}Blocks/Blocks_Core.xml',
     '        <requiresFaction>true</requiresFaction>\n',
     ''),
    ('X44 PN_Mod_Slabo z tekstem bazowym', '{DEFS}Blocks/Blocks_Core.xml',
     '         "skala") klocek nic nie stwierdza. Wplyw na moc i na wybor bez zmian. -->\n    <textFragment></textFragment>',
     '         "skala") klocek nic nie stwierdza. Wplyw na moc i na wybor bez zmian. -->\n    <textFragment>Rozmach jest mniejszy, niz moglby byc.</textFragment>'),
    ('X45 powtorzenie przy negatywnym warunku pamieci', '{DEFS}Blocks/Blocks_Consequences.xml',
     '<li Class="ProceduralNarrator.Core.Conditions.Cond_Fakt"><key>walka.byla</key></li>',
     '<li Class="ProceduralNarrator.Core.Conditions.Cond_Fakt"><key>walka.byla</key><required>false</required></li>'),
    ('X46 napad nocny bez warunku nocy', '{DEFS}Blocks/Blocks_Core.xml',
     '        <id>noc</id>\n        <conditions>\n          <li Class="ProceduralNarrator.Core.Conditions.Cond_Night" />\n        </conditions>\n        <text>nadciaga noca na kolonie.</text>',
     '        <id>noc</id>\n        <text>nadciaga noca na kolonie.</text>'),
    ('X47 wyjatkowo zamozna od 2x normy', '{DEFS}Blocks/Blocks_Core.xml',
     '<li Class="ProceduralNarrator.Core.Conditions.Cond_WealthRelative"><min>4</min></li>',
     '<li Class="ProceduralNarrator.Core.Conditions.Cond_WealthRelative"><min>2</min></li>'),
    # ---- krok 8, S10: tresc po przegladzie (decyzje autora, runda 3) ----
    ('X49 dzika zwierzyna znow wygryza sie spod podlogi', '{DEFS}Blocks/Blocks_Core.xml',
     'stwierdzalo nieprawde. -->\n      <li>PN_Aktor_Dzikie</li>\n',
     'stwierdzalo nieprawde. -->\n'),
    ('X50 dziki czlowiek znow przynosi wiesci', '{DEFS}Blocks/Blocks_Consequences.xml',
     'zdziczaly czlowiek nie przynosi wiesci. -->\n      <li>PN_Akcja_Dzikus</li>\n',
     'zdziczaly czlowiek nie przynosi wiesci. -->\n'),
    ('X51 mniejszy rozmach bez progu 300 punktow', '{DEFS}Blocks/Blocks_Core.xml',
     '        <conditions>\n          <li Class="ProceduralNarrator.Core.Conditions.Cond_MinThreatPoints"><min>300</min></li>\n        </conditions>\n',
     ''),
    ('X52 sprawa pierwszej wagi przy kazdej mocy', '{DEFS}Blocks/Blocks_Core.xml',
     '        <id>waga</id>\n        <minIntensity>High</minIntensity>\n',
     '        <id>waga</id>\n'),
    ('X53 sprawa drugorzedna z powrotem w tekscie bazowym', '{DEFS}Blocks/Blocks_Core.xml',
     'zdanie tylko przy mocy koncowej co najwyzej Low. -->\n    <textFragment></textFragment>',
     'zdanie tylko przy mocy koncowej co najwyzej Low. -->\n    <textFragment>Dla kolonii to na razie sprawa drugorzedna.</textFragment>'),
    ('X54 meteoryt znow pelen kruszcu', '{DEFS}Blocks/Blocks_Extended.xml',
     '    <textFragment>zrzuca w okolicy meteoryt.</textFragment>',
     '    <textFragment>zrzuca na teren kolonii meteoryt pelen kruszcu.</textFragment>'),
    ('X55 ciemnosc w tekscie bazowym bez warunku nocy', '{DEFS}Blocks/Blocks_Core.xml',
     '    <textFragment>wpada w szal i rusza na osade.</textFragment>',
     '    <textFragment>wpada w szal i po ciemku rusza na osade.</textFragment>'),
    ('X56 powtorzenie w tekscie bazowym', '{DEFS}Blocks/Blocks_Extended.xml',
     '    <textFragment>traci rozum i rzuca sie na kazdego, kogo napotka.</textFragment>',
     '    <textFragment>wciaz traci rozum i rzuca sie na kazdego, kogo napotka.</textFragment>'),
]


def sciezka(p):
    return p.replace('{SRC}', SRC).replace('{WALIDATOR}', WALIDATOR).replace('{DEFS}', DEFS)


def run_validator():
    """Zwraca (ok, bledow, linie_bledow, nie_kompiluje_sie).

    Brak podsumowania ma dwie rozne przyczyny i nie wolno ich mieszac: blad KOMPILACJI oznacza,
    ze mutacja w ogole nie weszla do testowanego kodu (niczego nie dowodzi - NIEWAZNA), a awaria
    w czasie dzialania (wyjatek) jest wykryciem - walidator padl na zmienionym zachowaniu.
    Kod bledu kompilatora (CSxxxx/MSBxxxx) nie jest tlumaczony, slowo przed nim bywa."""
    p = subprocess.run(['dotnet', 'run', '-c', 'Release'], cwd=WALIDATOR, capture_output=True, text=True,
                       encoding='utf-8', errors='replace', timeout=900)
    out = p.stdout + p.stderr
    m = re.search(r'PODSUMOWANIE: (\d+) OK, (\d+) BLEDOW', out)
    if not m:
        kompilacja = re.search(r'(error|b\u0142\u0105d)\s+(CS|MSB)\d{4}', out, re.IGNORECASE) is not None
        err = [l for l in out.splitlines() if 'error' in l or 'Exception' in l][:2]
        # Asercje, ktore padly PRZED awaria, sa czescia dowodu - bez nich plik wynikowy zanizal
        # sile wykrycia (przeglad S6: B8 i B20 mialy padniete asercje, a raport pokazywal tylko wyjatek).
        bledy = [l.strip() for l in out.splitlines() if l.strip().startswith('[BLAD]')]
        return None, None, bledy + err, kompilacja
    fails = [l.strip() for l in out.splitlines() if l.strip().startswith('[BLAD]')]
    return int(m.group(1)), int(m.group(2)), fails, False


def main():
    args = sys.argv[1:]
    tylko_sprawdz = '--sprawdz' in args
    wybrane = [a for a in args if not a.startswith('--')]
    wykryte = niewykryte = nieaktualne = niewazne = 0
    for name, path, old, new in INJ:
        if wybrane and name.split()[0] not in wybrane:
            continue
        path = sciezka(path)
        raw = io.open(path, 'rb').read()
        txt = raw.decode('utf-8')
        crlf = '\r\n' in txt
        norm = txt.replace('\r\n', '\n')
        if norm.count(old) != 1:
            nieaktualne += 1
            print('%-48s WZORZEC NIEAKTUALNY (wystapien: %d)' % (name, norm.count(old)))
            continue
        if tylko_sprawdz:
            print('%-48s wzorzec OK' % name)
            continue
        zm = norm.replace(old, new)
        if crlf:
            zm = zm.replace('\n', '\r\n')
        try:
            io.open(path, 'wb').write(zm.encode('utf-8'))
            ok, bad, fails, nie_kompiluje = run_validator()
        finally:
            io.open(path, 'wb').write(raw)
        if ok is None and nie_kompiluje:
            niewazne += 1
            print('%-48s *** NIEWAZNA: mutacja sie nie kompiluje *** %s' % (name, [f[:120] for f in fails]))
        elif ok is None:
            wykryte += 1
            print('%-48s PRZEBIEG PADL (wykryte przez awarie w czasie dzialania) %s'
                  % (name, [f[:120] for f in fails]))
        else:
            if bad > 0:
                wykryte += 1
            else:
                niewykryte += 1
            print('%-48s %s (%d bledow)' % (name, 'WYKRYTE' if bad > 0 else '*** NIEWYKRYTE ***', bad))
            for f in fails[:2]:
                print('      ' + f[:150].encode('ascii', 'replace').decode())
        sys.stdout.flush()
    print('PODSUMOWANIE MUTACJI: wykryte %d, NIEWYKRYTE %d, nieaktualne wzorce %d, NIEWAZNE %d'
          % (wykryte, niewykryte, nieaktualne, niewazne))
    if not tylko_sprawdz:
        ok, bad, _, _ = run_validator()
        print('PO PRZYWROCENIU:', ok, 'OK,', bad, 'BLEDOW')
    sys.exit(1 if (niewykryte or nieaktualne or niewazne) else 0)


if __name__ == '__main__':
    main()
